Category.find_by(name: 'その他').children.create!(name: 'ハンドクリーム')

PostItemCategory.create!(item: Item.find_by(item_number: 73), category: Category.find_by(name: '化粧下地')) if PostItemCategory.find_by(item: Item.find_by(item_number: 73)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 74), category: Category.find_by(name: 'ファンデーション')) if PostItemCategory.find_by(item: Item.find_by(item_number: 74)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 75), category: Category.find_by(name: 'メイク雑貨・小物')) if PostItemCategory.find_by(item: Item.find_by(item_number: 75)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 76), category: Category.find_by(name: 'コンシーラー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 76)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 77), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 77)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 78), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 78)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 79), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 79)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 80), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 80)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 81), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 81)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 82), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 82)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 84), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 84)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 85), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 85)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 86), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 86)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 87), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 87)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 88), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 88)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 89), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 89)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 90), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 90)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 91), category: Category.find_by(name: '美容液')) if PostItemCategory.find_by(item: Item.find_by(item_number: 91)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 92), category: Category.find_by(name: '美容液')) if PostItemCategory.find_by(item: Item.find_by(item_number: 92)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 93), category: Category.find_by(name: '乳液')) if PostItemCategory.find_by(item: Item.find_by(item_number: 93)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 94), category: Category.find_by(name: 'ハンドクリーム')) if PostItemCategory.find_by(item: Item.find_by(item_number: 94)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 96), category: Category.find_by(name: 'フェイスパウダー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 96)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 97), category: Category.find_by(name: 'チーク')) if PostItemCategory.find_by(item: Item.find_by(item_number: 97)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 98), category: Category.find_by(name: 'アイライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 98)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 99), category: Category.find_by(name: 'アイライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 99)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 100), category: Category.find_by(name: 'マスカラ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 100)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 101), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 101)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 102), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 102)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 103), category: Category.find_by(name: 'スキンケアクリーム')) if PostItemCategory.find_by(item: Item.find_by(item_number: 103)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 104), category: Category.find_by(name: 'スキンケアクリーム')) if PostItemCategory.find_by(item: Item.find_by(item_number: 104)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 105), category: Category.find_by(name: 'アイケア')) if PostItemCategory.find_by(item: Item.find_by(item_number: 105)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 106), category: Category.find_by(name: '美容液')) if PostItemCategory.find_by(item: Item.find_by(item_number: 106)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 107), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 107)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 108), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 108)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 109), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 109)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 110), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 110)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 111), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 111)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 112), category: Category.find_by(name: 'メイク雑貨・小物')) if PostItemCategory.find_by(item: Item.find_by(item_number: 112)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 113), category: Category.find_by(name: 'メイク雑貨・小物')) if PostItemCategory.find_by(item: Item.find_by(item_number: 113)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 114), category: Category.find_by(name: 'メイク雑貨・小物')) if PostItemCategory.find_by(item: Item.find_by(item_number: 114)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 116), category: Category.find_by(name: 'メイク雑貨・小物')) if PostItemCategory.find_by(item: Item.find_by(item_number: 116)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 119), category: Category.find_by(name: 'アイブロウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 119)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 120), category: Category.find_by(name: 'ハイライト')) if PostItemCategory.find_by(item: Item.find_by(item_number: 120)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 122), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 122)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 123), category: Category.find_by(name: 'コンシーラー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 123)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 124), category: Category.find_by(name: 'ファンデーション')) if PostItemCategory.find_by(item: Item.find_by(item_number: 124)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 125), category: Category.find_by(name: 'アイライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 125)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 126), category: Category.find_by(name: 'アイブロウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 126)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 127), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 127)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 128), category: Category.find_by(name: 'チーク')) if PostItemCategory.find_by(item: Item.find_by(item_number: 128)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 129), category: Category.find_by(name: 'シェーディング')) if PostItemCategory.find_by(item: Item.find_by(item_number: 129)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 131), category: Category.find_by(name: 'リップクリーム・リップケア')) if PostItemCategory.find_by(item: Item.find_by(item_number: 131)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 132), category: Category.find_by(name: '化粧下地')) if PostItemCategory.find_by(item: Item.find_by(item_number: 132)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 134), category: Category.find_by(name: 'コンシーラー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 134)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 135), category: Category.find_by(name: 'チーク')) if PostItemCategory.find_by(item: Item.find_by(item_number: 135)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 136), category: Category.find_by(name: 'シェーディング')) if PostItemCategory.find_by(item: Item.find_by(item_number: 136)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 138), category: Category.find_by(name: 'アイブロウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 138)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 139), category: Category.find_by(name: 'アイブロウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 139)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 140), category: Category.find_by(name: 'チーク')) if PostItemCategory.find_by(item: Item.find_by(item_number: 140)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 141), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 141)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 142), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 142)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 143), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 143)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 144), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 144)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 145), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 145)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 146), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 146)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 152), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 152)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 153), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 153)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 154), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 154)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 155), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 155)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 156), category: Category.find_by(name: 'ハイライト')) if PostItemCategory.find_by(item: Item.find_by(item_number: 156)).blank?