PostItemCategory.create!(item: Item.find_by(item_number: 246), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 246).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 246)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 247), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 247).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 247)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 249), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 249).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 249)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 253), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 253).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 253)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 254), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 254).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 254)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 255), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 255).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 255)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 256), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 256).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 256)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 257), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 257).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 257)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 258), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 258).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 258)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 259), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 259).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 259)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 260), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 260).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 260)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 261), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 261).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 261)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 262), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 262).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 262)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 263), category: Category.find_by(name: 'ハイライト')) if Item.find_by(item_number: 263).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 263)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 264), category: Category.find_by(name: 'ハイライト')) if Item.find_by(item_number: 264).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 264)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 265), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 265).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 265)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 266), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 266).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 266)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 267), category: Category.find_by(name: '化粧水')) if Item.find_by(item_number: 267).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 267)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 268), category: Category.find(20)) if Item.find_by(item_number: 268).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 268)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 269), category: Category.find(20)) if Item.find_by(item_number: 269).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 269)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 270), category: Category.find(20)) if Item.find_by(item_number: 270).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 270)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 271), category: Category.find(20)) if Item.find_by(item_number: 271).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 271)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 272), category: Category.find(20)) if Item.find_by(item_number: 272).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 272)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 273), category: Category.find(20)) if Item.find_by(item_number: 273).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 273)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 274), category: Category.find(20)) if Item.find_by(item_number: 274).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 274)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 275), category: Category.find(20)) if Item.find_by(item_number: 275).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 275)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 276), category: Category.find(20)) if Item.find_by(item_number: 276).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 276)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 277), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 277).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 277)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 278), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 278).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 278)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 279), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 279).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 279)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 280), category: Category.find_by(name: 'リップクリーム・リップケア')) if Item.find_by(item_number: 280).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 280)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 281), category: Category.find_by(name: 'リップクリーム・リップケア')) if Item.find_by(item_number: 281).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 281)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 282), category: Category.find_by(name: 'リップクリーム・リップケア')) if Item.find_by(item_number: 282).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 282)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 283), category: Category.find_by(name: 'メイク雑貨・小物')) if Item.find_by(item_number: 283).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 283)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 284), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 284).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 284)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 285), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 285).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 285)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 286), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 286).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 286)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 287), category: Category.find_by(name: 'リップクリーム・リップケア')) if Item.find_by(item_number: 287).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 287)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 288), category: Category.find_by(name: 'リップクリーム・リップケア')) if Item.find_by(item_number: 288).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 288)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 289), category: Category.find(20)) if Item.find_by(item_number: 289).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 289)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 290), category: Category.find(20)) if Item.find_by(item_number: 290).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 290)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 291), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 291).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 291)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 292), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 292).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 292)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 293), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 293).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 293)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 294), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 294).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 294)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 295), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 295).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 295)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 296), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 296).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 296)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 297), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 297).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 297)).blank?