Post.find_by(video_id: 'UeBXdnHjhXE').update(post_number: 1) if Post.find_by(video_id: 'UeBXdnHjhXE').present?
Post.find_by(video_id: '47YnnAAh3o0').update(post_number: 2) if Post.find_by(video_id: '47YnnAAh3o0').present?
Post.find_by(video_id: 'uLSE9dJcBVI').update(post_number: 3) if Post.find_by(video_id: 'uLSE9dJcBVI').present?
Post.find_by(video_id: 'vTeUxlZapeM').update(post_number: 4) if Post.find_by(video_id: 'vTeUxlZapeM').present?
Post.find_by(video_id: '4EAt82vGlFA').update(post_number: 5) if Post.find_by(video_id: '4EAt82vGlFA').present?
Post.find_by(video_id: 'YoI23FPPYvU').update(post_number: 6) if Post.find_by(video_id: 'YoI23FPPYvU').present?
Post.find_by(video_id: 'BVEccxsvOTI').update(post_number: 7) if Post.find_by(video_id: 'BVEccxsvOTI').present?
Post.find_by(video_id: 'JvbP1b8vfcI').update(post_number: 8) if Post.find_by(video_id: 'JvbP1b8vfcI').present?
Post.find_by(video_id: 'wke8qemihbM').update(post_number: 9) if Post.find_by(video_id: 'wke8qemihbM').present?
Post.find_by(video_id: 'wSilxSxRLds').update(post_number: 10) if Post.find_by(video_id: 'wSilxSxRLds').present?
Post.find_by(video_id: '7Gxi4CVUd2k').update(post_number: 11) if Post.find_by(video_id: '7Gxi4CVUd2k').present?
Post.find_by(video_id: 'ZC9PxFbX9aM').update(post_number: 12) if Post.find_by(video_id: 'ZC9PxFbX9aM').present?
Post.find_by(video_id: 'u2LEPiA0Lw8').update(post_number: 13) if Post.find_by(video_id: 'u2LEPiA0Lw8').present?
Post.find_by(video_id: '-mcjjv5RRB8').update(post_number: 14) if Post.find_by(video_id: '-mcjjv5RRB8').present?
Post.find_by(video_id: 'ol5au-Jcsjg').update(post_number: 15) if Post.find_by(video_id: 'ol5au-Jcsjg').present?
Post.find_by(video_id: 'JKNojeLXlUE').update(post_number: 16) if Post.find_by(video_id: 'JKNojeLXlUE').present?
Post.find_by(video_id: 'IkdjqnJWhVg').update(post_number: 17) if Post.find_by(video_id: 'IkdjqnJWhVg').present?
Post.find_by(video_id: 'M6gPEipd9CM').update(post_number: 18) if Post.find_by(video_id: 'M6gPEipd9CM').present?
Post.find_by(video_id: '3O78vBiCvAw').update(post_number: 19) if Post.find_by(video_id: '3O78vBiCvAw').present?
Post.find_by(video_id: 'd88qODe8sqk').update(post_number: 20) if Post.find_by(video_id: 'd88qODe8sqk').present?
Post.find_by(video_id: 'iR0_8rQtahE').update(post_number: 21) if Post.find_by(video_id: 'iR0_8rQtahE').present?
Post.find_by(video_id: 'oND8uQ8ZC_g').update(post_number: 22) if Post.find_by(video_id: 'oND8uQ8ZC_g').present?
Post.find_by(video_id: 'f6e5ig7QhMI').update(post_number: 23) if Post.find_by(video_id: 'f6e5ig7QhMI').present?
Post.find_by(video_id: 'D4AvdxUK7Rw').update(post_number: 24) if Post.find_by(video_id: 'D4AvdxUK7Rw').present?
Post.find_by(video_id: 'Nyryjtjs2oY').update(post_number: 25) if Post.find_by(video_id: 'Nyryjtjs2oY').present?
Post.find_by(video_id: 'uZNrQX69AYQ').update(post_number: 26) if Post.find_by(video_id: 'uZNrQX69AYQ').present?
Post.find_by(video_id: 'Hwa_QZSwGDQ').update(post_number: 27) if Post.find_by(video_id: 'Hwa_QZSwGDQ').present?
Post.find_by(video_id: '2pKFBCwmhLI').update(post_number: 28) if Post.find_by(video_id: '2pKFBCwmhLI').present?
Post.find_by(video_id: '3J6atLfe6jk').update(post_number: 29) if Post.find_by(video_id: '3J6atLfe6jk').present?
Post.find_by(video_id: 'qDNV3k6Y1kw').update(post_number: 30) if Post.find_by(video_id: 'qDNV3k6Y1kw').present?
Post.find_by(video_id: 'VTT6THDf6Oo').update(post_number: 31) if Post.find_by(video_id: 'VTT6THDf6Oo').present?
Post.find_by(video_id: '3w7w7PuWWos').update(post_number: 32) if Post.find_by(video_id: '3w7w7PuWWos').present?
Post.find_by(video_id: '3RqfYQ6ZmKs').update(post_number: 33) if Post.find_by(video_id: '3RqfYQ6ZmKs').present?
Post.find_by(video_id: 'WVh6grDbObM').update(post_number: 34) if Post.find_by(video_id: 'WVh6grDbObM').present?
Post.find_by(video_id: 'Rim1jL7koxo').update(post_number: 35) if Post.find_by(video_id: 'Rim1jL7koxo').present?
Post.find_by(video_id: 'p9jewXm6t4o').update(post_number: 36) if Post.find_by(video_id: 'p9jewXm6t4o').present?
Post.find_by(video_id: 'qqemCIPRypU').update(post_number: 37) if Post.find_by(video_id: 'qqemCIPRypU').present?
Post.find_by(video_id: '82XSamzH-lU').update(post_number: 38) if Post.find_by(video_id: '82XSamzH-lU').present?
Post.find_by(video_id: 'TDugKQOBf24').update(post_number: 39) if Post.find_by(video_id: 'TDugKQOBf24').present?
Post.find_by(video_id: 'Czy9AxKBUL8').update(post_number: 40) if Post.find_by(video_id: 'Czy9AxKBUL8').present?
Post.find_by(video_id: 'Sr6MUEbOzlI').update(post_number: 41) if Post.find_by(video_id: 'Sr6MUEbOzlI').present?
Post.find_by(video_id: 'U0YjhTa7EkU').update(post_number: 42) if Post.find_by(video_id: 'U0YjhTa7EkU').present?
Post.find_by(video_id: 'LbJXrPp6jSw').update(post_number: 43) if Post.find_by(video_id: 'LbJXrPp6jSw').present?
Post.find_by(video_id: 'HdL-uVPxB7Y').update(post_number: 44) if Post.find_by(video_id: 'HdL-uVPxB7Y').present?
Post.find_by(video_id: 'f5ybLfshhEI').update(post_number: 45) if Post.find_by(video_id: 'f5ybLfshhEI').present?
Post.find_by(video_id: 'HgaCP7aEtzc').update(post_number: 46) if Post.find_by(video_id: 'HgaCP7aEtzc').present?
Post.find_by(video_id: 'gm6khBUY8FU').update(post_number: 47) if Post.find_by(video_id: 'gm6khBUY8FU').present?
Post.find_by(video_id: 'Y6mgjunXBQk').update(post_number: 48) if Post.find_by(video_id: 'Y6mgjunXBQk').present?
Post.find_by(video_id: 'O1yWVCsSeDQ').update(post_number: 49) if Post.find_by(video_id: 'O1yWVCsSeDQ').present?
Post.find_by(video_id: 'edrlmswit7I').update(post_number: 50) if Post.find_by(video_id: 'edrlmswit7I').present?
Post.find_by(video_id: 'hViDh_7dWAI').update(post_number: 51) if Post.find_by(video_id: 'hViDh_7dWAI').present?
Post.find_by(video_id: 'vBpW7HZ1oHk').update(post_number: 52) if Post.find_by(video_id: 'vBpW7HZ1oHk').present?
Post.find_by(video_id: 'RtqG7R2U3EI').update(post_number: 53) if Post.find_by(video_id: 'RtqG7R2U3EI').present?
Post.find_by(video_id: 'Pjoh-ra-k7c').update(post_number: 54) if Post.find_by(video_id: 'Pjoh-ra-k7c').present?
Post.find_by(video_id: 'lXHOoLDCf2U').update(post_number: 55) if Post.find_by(video_id: 'lXHOoLDCf2U').present?
Post.find_by(video_id: 'm69scjIWKbE').update(post_number: 56) if Post.find_by(video_id: 'm69scjIWKbE').present?
Post.find_by(video_id: 'QfLqo3zRuPg').update(post_number: 57) if Post.find_by(video_id: 'QfLqo3zRuPg').present?
Post.find_by(video_id: 'SexBlIXkWCQ').update(post_number: 58) if Post.find_by(video_id: 'SexBlIXkWCQ').present?
Post.find_by(video_id: 'uRVxF5dQPIQ').update(post_number: 59) if Post.find_by(video_id: 'uRVxF5dQPIQ').present?
Post.find_by(video_id: 'Dxv8S1e_oA8').update(post_number: 60) if Post.find_by(video_id: 'Dxv8S1e_oA8').present?
Post.find_by(video_id: 'a5Pm2wlbpMc').update(post_number: 61) if Post.find_by(video_id: 'a5Pm2wlbpMc').present?
Post.find_by(video_id: 'WJXrYKm7yYA').update(post_number: 62) if Post.find_by(video_id: 'WJXrYKm7yYA').present?
Post.find_by(video_id: 'pfl7DbC84U4').update(post_number: 63) if Post.find_by(video_id: 'pfl7DbC84U4').present?
Post.find_by(video_id: '0Aq6NPPQpj0').update(post_number: 64) if Post.find_by(video_id: '0Aq6NPPQpj0').present?
Post.find_by(video_id: 'P3pgopRGoDQ').update(post_number: 65) if Post.find_by(video_id: 'P3pgopRGoDQ').present?
Post.find_by(video_id: 'Zr00hYpWPE4').update(post_number: 66) if Post.find_by(video_id: 'Zr00hYpWPE4').present?
Post.find_by(video_id: 'YuPfQh5YXTo').update(post_number: 67) if Post.find_by(video_id: 'YuPfQh5YXTo').present?
Post.find_by(video_id: 'jYNpKWb1MFM').update(post_number: 68) if Post.find_by(video_id: 'jYNpKWb1MFM').present?
Post.find_by(video_id: 'R0HBMJGtjsg').update(post_number: 69) if Post.find_by(video_id: 'R0HBMJGtjsg').present?
Post.find_by(video_id: 'fdUG2fw3HqU').update(post_number: 70) if Post.find_by(video_id: 'fdUG2fw3HqU').present?
Post.find_by(video_id: 'WpcNGUk7hwc').update(post_number: 71) if Post.find_by(video_id: 'WpcNGUk7hwc').present?
Post.find_by(video_id: 'JiUNN2AsigM').update(post_number: 72) if Post.find_by(video_id: 'JiUNN2AsigM').present?
Post.find_by(video_id: 'IP7HeEatZQI').update(post_number: 73) if Post.find_by(video_id: 'IP7HeEatZQI').present?
Post.find_by(video_id: '1BBBa5MVEoQ').update(post_number: 74) if Post.find_by(video_id: '1BBBa5MVEoQ').present?
Post.find_by(video_id: 'pJPtYiLvM5E').update(post_number: 75) if Post.find_by(video_id: 'pJPtYiLvM5E').present?
Post.find_by(video_id: 'Bi8oh69b-IA').update(post_number: 76) if Post.find_by(video_id: 'Bi8oh69b-IA').present?
Post.find_by(video_id: 'MOFtqS8Mhks').update(post_number: 77) if Post.find_by(video_id: 'MOFtqS8Mhks').present?
Post.find_by(video_id: 'UGKJtySS3oU').update(post_number: 78) if Post.find_by(video_id: 'UGKJtySS3oU').present?
Post.find_by(video_id: 'SmFumpYsRD8').update(post_number: 79) if Post.find_by(video_id: 'SmFumpYsRD8').present?
Post.find_by(video_id: 'GYV74j1Awt4').update(post_number: 80) if Post.find_by(video_id: 'GYV74j1Awt4').present?
Post.find_by(video_id: 'TBXqGfvkn9I').update(post_number: 81) if Post.find_by(video_id: 'TBXqGfvkn9I').present?
Post.find_by(video_id: 'd2lQ_vi1MGk').update(post_number: 82) if Post.find_by(video_id: 'd2lQ_vi1MGk').present?
Post.find_by(video_id: 'vdA-QTt3J7k').update(post_number: 83) if Post.find_by(video_id: 'vdA-QTt3J7k').present?
Post.find_by(video_id: 'GvqI_1_HDdw').update(post_number: 84) if Post.find_by(video_id: 'GvqI_1_HDdw').present?
Post.find_by(video_id: 'i6MmHtDkgsI').update(post_number: 85) if Post.find_by(video_id: 'i6MmHtDkgsI').present?
Post.find_by(video_id: 'Rq3CmwL8wO0').update(post_number: 86) if Post.find_by(video_id: 'Rq3CmwL8wO0').present?
Post.find_by(video_id: 'WMxRm5xJJlE').update(post_number: 87) if Post.find_by(video_id: 'WMxRm5xJJlE').present?
Post.find_by(video_id: '2wcjZsu9fGc').update(post_number: 88) if Post.find_by(video_id: '2wcjZsu9fGc').present?
Post.find_by(video_id: 'gXRELoIeVIQ').update(post_number: 89) if Post.find_by(video_id: 'gXRELoIeVIQ').present?
Post.find_by(video_id: 'i1VKYZiXfEs').update(post_number: 90) if Post.find_by(video_id: 'i1VKYZiXfEs').present?
Post.find_by(video_id: 'mPVRj7u4eM0').update(post_number: 91) if Post.find_by(video_id: 'mPVRj7u4eM0').present?
Post.find_by(video_id: 'FT8xYdI4308').update(post_number: 92) if Post.find_by(video_id: 'FT8xYdI4308').present?
Post.find_by(video_id: 'jiyZVyJ1vIo').update(post_number: 93) if Post.find_by(video_id: 'jiyZVyJ1vIo').present?
Post.find_by(video_id: 'v-hzeift2Fo').update(post_number: 94) if Post.find_by(video_id: 'v-hzeift2Fo').present?
Post.find_by(video_id: 'iz0w0_3qY8c').update(post_number: 95) if Post.find_by(video_id: 'iz0w0_3qY8c').present?
Post.find_by(video_id: 'rLqFNuiFU-A').update(post_number: 96) if Post.find_by(video_id: 'rLqFNuiFU-A').present?
Post.find_by(video_id: 'yq5Kln145N8').update(post_number: 97) if Post.find_by(video_id: 'yq5Kln145N8').present?
Post.find_by(video_id: 'xIa_CxT11XA').update(post_number: 98) if Post.find_by(video_id: 'xIa_CxT11XA').present?
Post.find_by(video_id: 'hKQlktqAf34').update(post_number: 99) if Post.find_by(video_id: 'hKQlktqAf34').present?
Post.find_by(video_id: 'JHUtsIugvWE').update(post_number: 100) if Post.find_by(video_id: 'JHUtsIugvWE').present?
Post.find_by(video_id: 'JWez7pyyZG4').update(post_number: 101) if Post.find_by(video_id: 'JWez7pyyZG4').present?
Post.find_by(video_id: 'MY7T3Ankfdw').update(post_number: 102) if Post.find_by(video_id: 'MY7T3Ankfdw').present?
Post.find_by(video_id: '4JBrR4TCtXs').update(post_number: 103) if Post.find_by(video_id: '4JBrR4TCtXs').present?