ItemPost.create!(post_id: 1, item_id: 1) if ItemPost.find_by(post_id: 1, item_id: 1).blank?
ItemPost.create!(post_id: 1, item_id: 2) if ItemPost.find_by(post_id: 1, item_id: 2).blank?
ItemPost.create!(post_id: 1, item_id: 3) if ItemPost.find_by(post_id: 1, item_id: 3).blank?
ItemPost.create!(post_id: 1, item_id: 4) if ItemPost.find_by(post_id: 1, item_id: 4).blank?
ItemPost.create!(post_id: 1, item_id: 5) if ItemPost.find_by(post_id: 1, item_id: 5).blank?
ItemPost.create!(post_id: 2, item_id: 6) if ItemPost.find_by(post_id: 2, item_id: 6).blank?
ItemPost.create!(post_id: 2, item_id: 7) if ItemPost.find_by(post_id: 2, item_id: 7).blank?
ItemPost.create!(post_id: 2, item_id: 8) if ItemPost.find_by(post_id: 2, item_id: 8).blank?
ItemPost.create!(post_id: 4, item_id: 9) if ItemPost.find_by(post_id: 4, item_id: 9).blank?
ItemPost.create!(post_id: 4, item_id: 10) if ItemPost.find_by(post_id: 4, item_id: 10).blank?