ItemPost.create!(post_id: 35, item: Item.find_by(item_number: 246)) if Item.find_by(item_number: 246).present? && ItemPost.find_by(post_id: 35, item: Item.find_by(item_number: 246)).blank?
ItemPost.create!(post_id: 35, item: Item.find_by(item_number: 247)) if Item.find_by(item_number: 247).present? && ItemPost.find_by(post_id: 35, item: Item.find_by(item_number: 247)).blank?
ItemPost.create!(post_id: 35, item: Item.find_by(item_number: 249)) if Item.find_by(item_number: 249).present? && ItemPost.find_by(post_id: 35, item: Item.find_by(item_number: 249)).blank?
ItemPost.create!(post_id: 35, item: Item.find_by(item_number: 253)) if Item.find_by(item_number: 253).present? && ItemPost.find_by(post_id: 35, item: Item.find_by(item_number: 253)).blank?
ItemPost.create!(post_id: 35, item: Item.find_by(item_number: 254)) if Item.find_by(item_number: 254).present? && ItemPost.find_by(post_id: 35, item: Item.find_by(item_number: 254)).blank?
ItemPost.create!(post_id: 35, item: Item.find_by(item_number: 255)) if Item.find_by(item_number: 255).present? && ItemPost.find_by(post_id: 35, item: Item.find_by(item_number: 255)).blank?
ItemPost.create!(post_id: 35, item: Item.find_by(item_number: 256)) if Item.find_by(item_number: 256).present? && ItemPost.find_by(post_id: 35, item: Item.find_by(item_number: 256)).blank?
ItemPost.create!(post_id: 35, item: Item.find_by(item_number: 257)) if Item.find_by(item_number: 257).present? && ItemPost.find_by(post_id: 35, item: Item.find_by(item_number: 257)).blank?
ItemPost.create!(post_id: 35, item: Item.find_by(item_number: 258)) if Item.find_by(item_number: 258).present? && ItemPost.find_by(post_id: 35, item: Item.find_by(item_number: 258)).blank?
ItemPost.create!(post_id: 35, item: Item.find_by(item_number: 259)) if Item.find_by(item_number: 259).present? && ItemPost.find_by(post_id: 35, item: Item.find_by(item_number: 259)).blank?
ItemPost.create!(post_id: 35, item: Item.find_by(item_number: 260)) if Item.find_by(item_number: 260).present? && ItemPost.find_by(post_id: 35, item: Item.find_by(item_number: 260)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 261)) if Item.find_by(item_number: 261).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 261)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 262)) if Item.find_by(item_number: 262).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 262)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 263)) if Item.find_by(item_number: 263).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 263)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 264)) if Item.find_by(item_number: 264).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 264)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 265)) if Item.find_by(item_number: 265).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 265)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 266)) if Item.find_by(item_number: 266).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 266)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 267)) if Item.find_by(item_number: 267).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 267)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 268)) if Item.find_by(item_number: 268).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 268)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 269)) if Item.find_by(item_number: 269).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 269)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 270)) if Item.find_by(item_number: 270).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 270)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 271)) if Item.find_by(item_number: 271).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 271)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 272)) if Item.find_by(item_number: 272).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 272)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 273)) if Item.find_by(item_number: 273).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 273)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 274)) if Item.find_by(item_number: 274).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 274)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 275)) if Item.find_by(item_number: 275).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 275)).blank?
ItemPost.create!(post_id: 36, item: Item.find_by(item_number: 276)) if Item.find_by(item_number: 276).present? && ItemPost.find_by(post_id: 36, item: Item.find_by(item_number: 276)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 277)) if Item.find_by(item_number: 277).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 277)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 278)) if Item.find_by(item_number: 278).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 278)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 279)) if Item.find_by(item_number: 279).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 279)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 280)) if Item.find_by(item_number: 280).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 280)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 281)) if Item.find_by(item_number: 281).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 281)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 282)) if Item.find_by(item_number: 282).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 282)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 283)) if Item.find_by(item_number: 283).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 283)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 284)) if Item.find_by(item_number: 284).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 284)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 285)) if Item.find_by(item_number: 285).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 285)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 286)) if Item.find_by(item_number: 286).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 286)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 287)) if Item.find_by(item_number: 287).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 287)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 288)) if Item.find_by(item_number: 288).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 288)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 289)) if Item.find_by(item_number: 289).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 289)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 290)) if Item.find_by(item_number: 290).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 290)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 291)) if Item.find_by(item_number: 291).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 291)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 292)) if Item.find_by(item_number: 292).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 292)).blank?
ItemPost.create!(post_id: 37, item: Item.find_by(item_number: 293)) if Item.find_by(item_number: 293).present? && ItemPost.find_by(post_id: 37, item: Item.find_by(item_number: 293)).blank?
ItemPost.create!(post_id: 38, item: Item.find_by(item_number: 294)) if Item.find_by(item_number: 294).present? && ItemPost.find_by(post_id: 38, item: Item.find_by(item_number: 294)).blank?
ItemPost.create!(post_id: 38, item: Item.find_by(item_number: 295)) if Item.find_by(item_number: 295).present? && ItemPost.find_by(post_id: 38, item: Item.find_by(item_number: 295)).blank?
ItemPost.create!(post_id: 39, item: Item.find_by(item_number: 296)) if Item.find_by(item_number: 296).present? && ItemPost.find_by(post_id: 39, item: Item.find_by(item_number: 296)).blank?
ItemPost.create!(post_id: 39, item: Item.find_by(item_number: 297)) if Item.find_by(item_number: 297).present? && ItemPost.find_by(post_id: 39, item: Item.find_by(item_number: 297)).blank?