ItemPost.create!(post_id: 88, item: Item.find_by(item_number: 633)) if Item.find_by(item_number: 633).present? && ItemPost.find_by(post_id: 88, item: Item.find_by(item_number: 633)).blank?
ItemPost.create!(post_id: 88, item: Item.find_by(item_number: 634)) if Item.find_by(item_number: 634).present? && ItemPost.find_by(post_id: 88, item: Item.find_by(item_number: 634)).blank?
ItemPost.create!(post_id: 88, item: Item.find_by(item_number: 635)) if Item.find_by(item_number: 635).present? && ItemPost.find_by(post_id: 88, item: Item.find_by(item_number: 635)).blank?
ItemPost.create!(post_id: 88, item: Item.find_by(item_number: 636)) if Item.find_by(item_number: 636).present? && ItemPost.find_by(post_id: 88, item: Item.find_by(item_number: 636)).blank?
ItemPost.create!(post_id: 88, item: Item.find_by(item_number: 637)) if Item.find_by(item_number: 637).present? && ItemPost.find_by(post_id: 88, item: Item.find_by(item_number: 637)).blank?
ItemPost.create!(post_id: 88, item: Item.find_by(item_number: 638)) if Item.find_by(item_number: 638).present? && ItemPost.find_by(post_id: 88, item: Item.find_by(item_number: 638)).blank?
ItemPost.create!(post_id: 89, item: Item.find_by(item_number: 639)) if Item.find_by(item_number: 639).present? && ItemPost.find_by(post_id: 89, item: Item.find_by(item_number: 639)).blank?
ItemPost.create!(post_id: 89, item: Item.find_by(item_number: 640)) if Item.find_by(item_number: 640).present? && ItemPost.find_by(post_id: 89, item: Item.find_by(item_number: 640)).blank?
ItemPost.create!(post_id: 89, item: Item.find_by(item_number: 641)) if Item.find_by(item_number: 641).present? && ItemPost.find_by(post_id: 89, item: Item.find_by(item_number: 641)).blank?
ItemPost.create!(post_id: 89, item: Item.find_by(item_number: 643)) if Item.find_by(item_number: 643).present? && ItemPost.find_by(post_id: 89, item: Item.find_by(item_number: 643)).blank?
ItemPost.create!(post_id: 89, item: Item.find_by(item_number: 644)) if Item.find_by(item_number: 644).present? && ItemPost.find_by(post_id: 89, item: Item.find_by(item_number: 644)).blank?
ItemPost.create!(post_id: 90, item: Item.find_by(item_number: 649)) if Item.find_by(item_number: 649).present? && ItemPost.find_by(post_id: 90, item: Item.find_by(item_number: 649)).blank?
ItemPost.create!(post_id: 91, item: Item.find_by(item_number: 650)) if Item.find_by(item_number: 650).present? && ItemPost.find_by(post_id: 91, item: Item.find_by(item_number: 650)).blank?
ItemPost.create!(post_id: 91, item: Item.find_by(item_number: 651)) if Item.find_by(item_number: 651).present? && ItemPost.find_by(post_id: 91, item: Item.find_by(item_number: 651)).blank?
ItemPost.create!(post_id: 91, item: Item.find_by(item_number: 652)) if Item.find_by(item_number: 652).present? && ItemPost.find_by(post_id: 91, item: Item.find_by(item_number: 652)).blank?
ItemPost.create!(post_id: 91, item: Item.find_by(item_number: 653)) if Item.find_by(item_number: 653).present? && ItemPost.find_by(post_id: 91, item: Item.find_by(item_number: 653)).blank?
ItemPost.create!(post_id: 91, item: Item.find_by(item_number: 654)) if Item.find_by(item_number: 654).present? && ItemPost.find_by(post_id: 91, item: Item.find_by(item_number: 654)).blank?
ItemPost.create!(post_id: 91, item: Item.find_by(item_number: 655)) if Item.find_by(item_number: 655).present? && ItemPost.find_by(post_id: 91, item: Item.find_by(item_number: 655)).blank?
ItemPost.create!(post_id: 92, item: Item.find_by(item_number: 657)) if Item.find_by(item_number: 657).present? && ItemPost.find_by(post_id: 92, item: Item.find_by(item_number: 657)).blank?
ItemPost.create!(post_id: 92, item: Item.find_by(item_number: 658)) if Item.find_by(item_number: 658).present? && ItemPost.find_by(post_id: 92, item: Item.find_by(item_number: 658)).blank?
ItemPost.create!(post_id: 92, item: Item.find_by(item_number: 659)) if Item.find_by(item_number: 659).present? && ItemPost.find_by(post_id: 92, item: Item.find_by(item_number: 659)).blank?
ItemPost.create!(post_id: 92, item: Item.find_by(item_number: 660)) if Item.find_by(item_number: 660).present? && ItemPost.find_by(post_id: 92, item: Item.find_by(item_number: 660)).blank?
ItemPost.create!(post_id: 92, item: Item.find_by(item_number: 661)) if Item.find_by(item_number: 661).present? && ItemPost.find_by(post_id: 92, item: Item.find_by(item_number: 661)).blank?
ItemPost.create!(post_id: 92, item: Item.find_by(item_number: 662)) if Item.find_by(item_number: 662).present? && ItemPost.find_by(post_id: 92, item: Item.find_by(item_number: 662)).blank?
ItemPost.create!(post_id: 92, item: Item.find_by(item_number: 663)) if Item.find_by(item_number: 663).present? && ItemPost.find_by(post_id: 92, item: Item.find_by(item_number: 663)).blank?
ItemPost.create!(post_id: 92, item: Item.find_by(item_number: 664)) if Item.find_by(item_number: 664).present? && ItemPost.find_by(post_id: 92, item: Item.find_by(item_number: 664)).blank?
ItemPost.create!(post_id: 92, item: Item.find_by(item_number: 666)) if Item.find_by(item_number: 666).present? && ItemPost.find_by(post_id: 92, item: Item.find_by(item_number: 666)).blank?
ItemPost.create!(post_id: 92, item: Item.find_by(item_number: 667)) if Item.find_by(item_number: 667).present? && ItemPost.find_by(post_id: 92, item: Item.find_by(item_number: 667)).blank?
ItemPost.create!(post_id: 92, item: Item.find_by(item_number: 668)) if Item.find_by(item_number: 668).present? && ItemPost.find_by(post_id: 92, item: Item.find_by(item_number: 668)).blank?
ItemPost.create!(post_id: 92, item: Item.find_by(item_number: 669)) if Item.find_by(item_number: 669).present? && ItemPost.find_by(post_id: 92, item: Item.find_by(item_number: 669)).blank?
ItemPost.create!(post_id: 94, item: Item.find_by(item_number: 671)) if Item.find_by(item_number: 671).present? && ItemPost.find_by(post_id: 94, item: Item.find_by(item_number: 671)).blank?
ItemPost.create!(post_id: 94, item: Item.find_by(item_number: 673)) if Item.find_by(item_number: 673).present? && ItemPost.find_by(post_id: 94, item: Item.find_by(item_number: 673)).blank?
ItemPost.create!(post_id: 94, item: Item.find_by(item_number: 675)) if Item.find_by(item_number: 675).present? && ItemPost.find_by(post_id: 94, item: Item.find_by(item_number: 675)).blank?
ItemPost.create!(post_id: 94, item: Item.find_by(item_number: 677)) if Item.find_by(item_number: 677).present? && ItemPost.find_by(post_id: 94, item: Item.find_by(item_number: 677)).blank?
ItemPost.create!(post_id: 94, item: Item.find_by(item_number: 678)) if Item.find_by(item_number: 678).present? && ItemPost.find_by(post_id: 94, item: Item.find_by(item_number: 678)).blank?
ItemPost.create!(post_id: 94, item: Item.find_by(item_number: 679)) if Item.find_by(item_number: 679).present? && ItemPost.find_by(post_id: 94, item: Item.find_by(item_number: 679)).blank?
ItemPost.create!(post_id: 94, item: Item.find_by(item_number: 680)) if Item.find_by(item_number: 680).present? && ItemPost.find_by(post_id: 94, item: Item.find_by(item_number: 680)).blank?
ItemPost.create!(post_id: 95, item: Item.find_by(item_number: 681)) if Item.find_by(item_number: 681).present? && ItemPost.find_by(post_id: 95, item: Item.find_by(item_number: 681)).blank?
ItemPost.create!(post_id: 96, item: Item.find_by(item_number: 683)) if Item.find_by(item_number: 683).present? && ItemPost.find_by(post_id: 96, item: Item.find_by(item_number: 683)).blank?
ItemPost.create!(post_id: 96, item: Item.find_by(item_number: 684)) if Item.find_by(item_number: 684).present? && ItemPost.find_by(post_id: 96, item: Item.find_by(item_number: 684)).blank?
ItemPost.create!(post_id: 96, item: Item.find_by(item_number: 685)) if Item.find_by(item_number: 685).present? && ItemPost.find_by(post_id: 96, item: Item.find_by(item_number: 685)).blank?
ItemPost.create!(post_id: 96, item: Item.find_by(item_number: 686)) if Item.find_by(item_number: 686).present? && ItemPost.find_by(post_id: 96, item: Item.find_by(item_number: 686)).blank?
ItemPost.create!(post_id: 96, item: Item.find_by(item_number: 687)) if Item.find_by(item_number: 687).present? && ItemPost.find_by(post_id: 96, item: Item.find_by(item_number: 687)).blank?
ItemPost.create!(post_id: 96, item: Item.find_by(item_number: 688)) if Item.find_by(item_number: 688).present? && ItemPost.find_by(post_id: 96, item: Item.find_by(item_number: 688)).blank?
ItemPost.create!(post_id: 96, item: Item.find_by(item_number: 689)) if Item.find_by(item_number: 689).present? && ItemPost.find_by(post_id: 96, item: Item.find_by(item_number: 689)).blank?
ItemPost.create!(post_id: 96, item: Item.find_by(item_number: 690)) if Item.find_by(item_number: 690).present? && ItemPost.find_by(post_id: 96, item: Item.find_by(item_number: 690)).blank?
ItemPost.create!(post_id: 96, item: Item.find_by(item_number: 691)) if Item.find_by(item_number: 691).present? && ItemPost.find_by(post_id: 96, item: Item.find_by(item_number: 691)).blank?
ItemPost.create!(post_id: 96, item: Item.find_by(item_number: 692)) if Item.find_by(item_number: 692).present? && ItemPost.find_by(post_id: 96, item: Item.find_by(item_number: 692)).blank?
ItemPost.create!(post_id: 97, item: Item.find_by(item_number: 693)) if Item.find_by(item_number: 693).present? && ItemPost.find_by(post_id: 97, item: Item.find_by(item_number: 693)).blank?
ItemPost.create!(post_id: 97, item: Item.find_by(item_number: 694)) if Item.find_by(item_number: 694).present? && ItemPost.find_by(post_id: 97, item: Item.find_by(item_number: 694)).blank?
ItemPost.create!(post_id: 98, item: Item.find_by(item_number: 695)) if Item.find_by(item_number: 695).present? && ItemPost.find_by(post_id: 98, item: Item.find_by(item_number: 695)).blank?
ItemPost.create!(post_id: 98, item: Item.find_by(item_number: 697)) if Item.find_by(item_number: 697).present? && ItemPost.find_by(post_id: 98, item: Item.find_by(item_number: 697)).blank?
ItemPost.create!(post_id: 98, item: Item.find_by(item_number: 698)) if Item.find_by(item_number: 698).present? && ItemPost.find_by(post_id: 98, item: Item.find_by(item_number: 698)).blank?
ItemPost.create!(post_id: 98, item: Item.find_by(item_number: 699)) if Item.find_by(item_number: 699).present? && ItemPost.find_by(post_id: 98, item: Item.find_by(item_number: 699)).blank?
ItemPost.create!(post_id: 99, item: Item.find_by(item_number: 700)) if Item.find_by(item_number: 700).present? && ItemPost.find_by(post_id: 99, item: Item.find_by(item_number: 700)).blank?
ItemPost.create!(post_id: 99, item: Item.find_by(item_number: 702)) if Item.find_by(item_number: 702).present? && ItemPost.find_by(post_id: 99, item: Item.find_by(item_number: 702)).blank?
ItemPost.create!(post_id: 100, item: Item.find_by(item_number: 704)) if Item.find_by(item_number: 704).present? && ItemPost.find_by(post_id: 100, item: Item.find_by(item_number: 704)).blank?
ItemPost.create!(post_id: 100, item: Item.find_by(item_number: 705)) if Item.find_by(item_number: 705).present? && ItemPost.find_by(post_id: 100, item: Item.find_by(item_number: 705)).blank?
ItemPost.create!(post_id: 101, item: Item.find_by(item_number: 708)) if Item.find_by(item_number: 708).present? && ItemPost.find_by(post_id: 101, item: Item.find_by(item_number: 708)).blank?
ItemPost.create!(post_id: 101, item: Item.find_by(item_number: 709)) if Item.find_by(item_number: 709).present? && ItemPost.find_by(post_id: 101, item: Item.find_by(item_number: 709)).blank?
ItemPost.create!(post_id: 101, item: Item.find_by(item_number: 710)) if Item.find_by(item_number: 710).present? && ItemPost.find_by(post_id: 101, item: Item.find_by(item_number: 710)).blank?
ItemPost.create!(post_id: 101, item: Item.find_by(item_number: 711)) if Item.find_by(item_number: 711).present? && ItemPost.find_by(post_id: 101, item: Item.find_by(item_number: 711)).blank?
ItemPost.create!(post_id: 101, item: Item.find_by(item_number: 712)) if Item.find_by(item_number: 712).present? && ItemPost.find_by(post_id: 101, item: Item.find_by(item_number: 712)).blank?
ItemPost.create!(post_id: 101, item: Item.find_by(item_number: 713)) if Item.find_by(item_number: 713).present? && ItemPost.find_by(post_id: 101, item: Item.find_by(item_number: 713)).blank?
ItemPost.create!(post_id: 101, item: Item.find_by(item_number: 714)) if Item.find_by(item_number: 714).present? && ItemPost.find_by(post_id: 101, item: Item.find_by(item_number: 714)).blank?
ItemPost.create!(post_id: 101, item: Item.find_by(item_number: 715)) if Item.find_by(item_number: 715).present? && ItemPost.find_by(post_id: 101, item: Item.find_by(item_number: 715)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 716)) if Item.find_by(item_number: 716).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 716)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 717)) if Item.find_by(item_number: 717).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 717)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 718)) if Item.find_by(item_number: 718).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 718)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 719)) if Item.find_by(item_number: 719).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 719)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 720)) if Item.find_by(item_number: 720).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 720)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 721)) if Item.find_by(item_number: 721).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 721)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 722)) if Item.find_by(item_number: 722).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 722)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 723)) if Item.find_by(item_number: 723).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 723)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 724)) if Item.find_by(item_number: 724).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 724)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 725)) if Item.find_by(item_number: 725).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 725)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 726)) if Item.find_by(item_number: 726).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 726)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 727)) if Item.find_by(item_number: 727).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 727)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 728)) if Item.find_by(item_number: 728).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 728)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 729)) if Item.find_by(item_number: 729).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 729)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 730)) if Item.find_by(item_number: 730).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 730)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 731)) if Item.find_by(item_number: 731).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 731)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 732)) if Item.find_by(item_number: 732).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 732)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 733)) if Item.find_by(item_number: 733).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 733)).blank?
ItemPost.create!(post_id: 102, item: Item.find_by(item_number: 735)) if Item.find_by(item_number: 735).present? && ItemPost.find_by(post_id: 102, item: Item.find_by(item_number: 735)).blank?
ItemPost.create!(post_id: 103, item: Item.find_by(item_number: 737)) if Item.find_by(item_number: 737).present? && ItemPost.find_by(post_id: 103, item: Item.find_by(item_number: 737)).blank?
ItemPost.create!(post_id: 103, item: Item.find_by(item_number: 738)) if Item.find_by(item_number: 738).present? && ItemPost.find_by(post_id: 103, item: Item.find_by(item_number: 738)).blank?
ItemPost.create!(post_id: 103, item: Item.find_by(item_number: 739)) if Item.find_by(item_number: 739).present? && ItemPost.find_by(post_id: 103, item: Item.find_by(item_number: 739)).blank?
ItemPost.create!(post_id: 103, item: Item.find_by(item_number: 740)) if Item.find_by(item_number: 740).present? && ItemPost.find_by(post_id: 103, item: Item.find_by(item_number: 740)).blank?
ItemPost.create!(post_id: 103, item: Item.find_by(item_number: 741)) if Item.find_by(item_number: 741).present? && ItemPost.find_by(post_id: 103, item: Item.find_by(item_number: 741)).blank?
ItemPost.create!(post_id: 103, item: Item.find_by(item_number: 742)) if Item.find_by(item_number: 742).present? && ItemPost.find_by(post_id: 103, item: Item.find_by(item_number: 742)).blank?
ItemPost.create!(post_id: 103, item: Item.find_by(item_number: 743)) if Item.find_by(item_number: 743).present? && ItemPost.find_by(post_id: 103, item: Item.find_by(item_number: 743)).blank?
ItemPost.create!(post_id: 103, item: Item.find_by(item_number: 744)) if Item.find_by(item_number: 744).present? && ItemPost.find_by(post_id: 103, item: Item.find_by(item_number: 744)).blank?
ItemPost.create!(post_id: 103, item: Item.find_by(item_number: 745)) if Item.find_by(item_number: 745).present? && ItemPost.find_by(post_id: 103, item: Item.find_by(item_number: 745)).blank?