ItemPost.create!(post_id: 38, item: Item.find_by(item_number: 294)) if Item.find_by(item_number: 294).present? && ItemPost.find_by(post_id: 38, item: Item.find_by(item_number: 294)).blank?
ItemPost.create!(post_id: 38, item: Item.find_by(item_number: 295)) if Item.find_by(item_number: 295).present? && ItemPost.find_by(post_id: 38, item: Item.find_by(item_number: 295)).blank?
ItemPost.create!(post_id: 39, item: Item.find_by(item_number: 296)) if Item.find_by(item_number: 296).present? && ItemPost.find_by(post_id: 39, item: Item.find_by(item_number: 296)).blank?
ItemPost.create!(post_id: 39, item: Item.find_by(item_number: 297)) if Item.find_by(item_number: 297).present? && ItemPost.find_by(post_id: 39, item: Item.find_by(item_number: 297)).blank?
ItemPost.create!(post_id: 39, item: Item.find_by(item_number: 298)) if Item.find_by(item_number: 298).present? && ItemPost.find_by(post_id: 39, item: Item.find_by(item_number: 298)).blank?
ItemPost.create!(post_id: 39, item: Item.find_by(item_number: 299)) if Item.find_by(item_number: 299).present? && ItemPost.find_by(post_id: 39, item: Item.find_by(item_number: 299)).blank?
ItemPost.create!(post_id: 39, item: Item.find_by(item_number: 300)) if Item.find_by(item_number: 300).present? && ItemPost.find_by(post_id: 39, item: Item.find_by(item_number: 300)).blank?
ItemPost.create!(post_id: 39, item: Item.find_by(item_number: 301)) if Item.find_by(item_number: 301).present? && ItemPost.find_by(post_id: 39, item: Item.find_by(item_number: 301)).blank?
ItemPost.create!(post_id: 39, item: Item.find_by(item_number: 302)) if Item.find_by(item_number: 302).present? && ItemPost.find_by(post_id: 39, item: Item.find_by(item_number: 302)).blank?
ItemPost.create!(post_id: 39, item: Item.find_by(item_number: 303)) if Item.find_by(item_number: 303).present? && ItemPost.find_by(post_id: 39, item: Item.find_by(item_number: 303)).blank?
ItemPost.create!(post_id: 39, item: Item.find_by(item_number: 304)) if Item.find_by(item_number: 304).present? && ItemPost.find_by(post_id: 39, item: Item.find_by(item_number: 304)).blank?
ItemPost.create!(post_id: 39, item: Item.find_by(item_number: 305)) if Item.find_by(item_number: 305).present? && ItemPost.find_by(post_id: 39, item: Item.find_by(item_number: 305)).blank?
ItemPost.create!(post_id: 40, item: Item.find_by(item_number: 306)) if Item.find_by(item_number: 306).present? && ItemPost.find_by(post_id: 40, item: Item.find_by(item_number: 306)).blank?
ItemPost.create!(post_id: 40, item: Item.find_by(item_number: 307)) if Item.find_by(item_number: 307).present? && ItemPost.find_by(post_id: 40, item: Item.find_by(item_number: 307)).blank?
ItemPost.create!(post_id: 41, item: Item.find_by(item_number: 308)) if Item.find_by(item_number: 308).present? && ItemPost.find_by(post_id: 41, item: Item.find_by(item_number: 308)).blank?
ItemPost.create!(post_id: 41, item: Item.find_by(item_number: 309)) if Item.find_by(item_number: 309).present? && ItemPost.find_by(post_id: 41, item: Item.find_by(item_number: 309)).blank?
ItemPost.create!(post_id: 41, item: Item.find_by(item_number: 310)) if Item.find_by(item_number: 310).present? && ItemPost.find_by(post_id: 41, item: Item.find_by(item_number: 310)).blank?
ItemPost.create!(post_id: 41, item: Item.find_by(item_number: 311)) if Item.find_by(item_number: 311).present? && ItemPost.find_by(post_id: 41, item: Item.find_by(item_number: 311)).blank?
ItemPost.create!(post_id: 41, item: Item.find_by(item_number: 312)) if Item.find_by(item_number: 312).present? && ItemPost.find_by(post_id: 41, item: Item.find_by(item_number: 312)).blank?
ItemPost.create!(post_id: 41, item: Item.find_by(item_number: 313)) if Item.find_by(item_number: 313).present? && ItemPost.find_by(post_id: 41, item: Item.find_by(item_number: 313)).blank?
ItemPost.create!(post_id: 41, item: Item.find_by(item_number: 314)) if Item.find_by(item_number: 314).present? && ItemPost.find_by(post_id: 41, item: Item.find_by(item_number: 314)).blank?
ItemPost.create!(post_id: 41, item: Item.find_by(item_number: 315)) if Item.find_by(item_number: 315).present? && ItemPost.find_by(post_id: 41, item: Item.find_by(item_number: 315)).blank?
ItemPost.create!(post_id: 41, item: Item.find_by(item_number: 316)) if Item.find_by(item_number: 316).present? && ItemPost.find_by(post_id: 41, item: Item.find_by(item_number: 316)).blank?
ItemPost.create!(post_id: 41, item: Item.find_by(item_number: 317)) if Item.find_by(item_number: 317).present? && ItemPost.find_by(post_id: 41, item: Item.find_by(item_number: 317)).blank?
ItemPost.create!(post_id: 42, item: Item.find_by(item_number: 318)) if Item.find_by(item_number: 318).present? && ItemPost.find_by(post_id: 42, item: Item.find_by(item_number: 318)).blank?
ItemPost.create!(post_id: 42, item: Item.find_by(item_number: 319)) if Item.find_by(item_number: 319).present? && ItemPost.find_by(post_id: 42, item: Item.find_by(item_number: 319)).blank?
ItemPost.create!(post_id: 42, item: Item.find_by(item_number: 320)) if Item.find_by(item_number: 320).present? && ItemPost.find_by(post_id: 42, item: Item.find_by(item_number: 320)).blank?
ItemPost.create!(post_id: 42, item: Item.find_by(item_number: 321)) if Item.find_by(item_number: 321).present? && ItemPost.find_by(post_id: 42, item: Item.find_by(item_number: 321)).blank?
ItemPost.create!(post_id: 42, item: Item.find_by(item_number: 322)) if Item.find_by(item_number: 322).present? && ItemPost.find_by(post_id: 42, item: Item.find_by(item_number: 322)).blank?
ItemPost.create!(post_id: 42, item: Item.find_by(item_number: 323)) if Item.find_by(item_number: 323).present? && ItemPost.find_by(post_id: 42, item: Item.find_by(item_number: 323)).blank?
ItemPost.create!(post_id: 42, item: Item.find_by(item_number: 324)) if Item.find_by(item_number: 324).present? && ItemPost.find_by(post_id: 42, item: Item.find_by(item_number: 324)).blank?
ItemPost.create!(post_id: 42, item: Item.find_by(item_number: 325)) if Item.find_by(item_number: 325).present? && ItemPost.find_by(post_id: 42, item: Item.find_by(item_number: 325)).blank?
ItemPost.create!(post_id: 42, item: Item.find_by(item_number: 326)) if Item.find_by(item_number: 326).present? && ItemPost.find_by(post_id: 42, item: Item.find_by(item_number: 326)).blank?
ItemPost.create!(post_id: 42, item: Item.find_by(item_number: 327)) if Item.find_by(item_number: 327).present? && ItemPost.find_by(post_id: 42, item: Item.find_by(item_number: 327)).blank?
ItemPost.create!(post_id: 43, item: Item.find_by(item_number: 328)) if Item.find_by(item_number: 328).present? && ItemPost.find_by(post_id: 43, item: Item.find_by(item_number: 328)).blank?
ItemPost.create!(post_id: 43, item: Item.find_by(item_number: 329)) if Item.find_by(item_number: 329).present? && ItemPost.find_by(post_id: 43, item: Item.find_by(item_number: 329)).blank?
ItemPost.create!(post_id: 43, item: Item.find_by(item_number: 330)) if Item.find_by(item_number: 330).present? && ItemPost.find_by(post_id: 43, item: Item.find_by(item_number: 330)).blank?
ItemPost.create!(post_id: 43, item: Item.find_by(item_number: 331)) if Item.find_by(item_number: 331).present? && ItemPost.find_by(post_id: 43, item: Item.find_by(item_number: 331)).blank?
ItemPost.create!(post_id: 44, item: Item.find_by(item_number: 332)) if Item.find_by(item_number: 332).present? && ItemPost.find_by(post_id: 44, item: Item.find_by(item_number: 332)).blank?
ItemPost.create!(post_id: 44, item: Item.find_by(item_number: 333)) if Item.find_by(item_number: 333).present? && ItemPost.find_by(post_id: 44, item: Item.find_by(item_number: 333)).blank?
ItemPost.create!(post_id: 44, item: Item.find_by(item_number: 334)) if Item.find_by(item_number: 334).present? && ItemPost.find_by(post_id: 44, item: Item.find_by(item_number: 334)).blank?
ItemPost.create!(post_id: 44, item: Item.find_by(item_number: 335)) if Item.find_by(item_number: 335).present? && ItemPost.find_by(post_id: 44, item: Item.find_by(item_number: 335)).blank?
ItemPost.create!(post_id: 44, item: Item.find_by(item_number: 336)) if Item.find_by(item_number: 336).present? && ItemPost.find_by(post_id: 44, item: Item.find_by(item_number: 336)).blank?
ItemPost.create!(post_id: 44, item: Item.find_by(item_number: 337)) if Item.find_by(item_number: 337).present? && ItemPost.find_by(post_id: 44, item: Item.find_by(item_number: 337)).blank?
ItemPost.create!(post_id: 44, item: Item.find_by(item_number: 338)) if Item.find_by(item_number: 338).present? && ItemPost.find_by(post_id: 44, item: Item.find_by(item_number: 338)).blank?
ItemPost.create!(post_id: 44, item: Item.find_by(item_number: 339)) if Item.find_by(item_number: 339).present? && ItemPost.find_by(post_id: 44, item: Item.find_by(item_number: 339)).blank?
ItemPost.create!(post_id: 44, item: Item.find_by(item_number: 340)) if Item.find_by(item_number: 340).present? && ItemPost.find_by(post_id: 44, item: Item.find_by(item_number: 340)).blank?
ItemPost.create!(post_id: 44, item: Item.find_by(item_number: 341)) if Item.find_by(item_number: 341).present? && ItemPost.find_by(post_id: 44, item: Item.find_by(item_number: 341)).blank?
ItemPost.create!(post_id: 44, item: Item.find_by(item_number: 342)) if Item.find_by(item_number: 342).present? && ItemPost.find_by(post_id: 44, item: Item.find_by(item_number: 342)).blank?
ItemPost.create!(post_id: 45, item: Item.find_by(item_number: 343)) if Item.find_by(item_number: 343).present? && ItemPost.find_by(post_id: 45, item: Item.find_by(item_number: 343)).blank?
ItemPost.create!(post_id: 45, item: Item.find_by(item_number: 344)) if Item.find_by(item_number: 344).present? && ItemPost.find_by(post_id: 45, item: Item.find_by(item_number: 344)).blank?
ItemPost.create!(post_id: 45, item: Item.find_by(item_number: 345)) if Item.find_by(item_number: 345).present? && ItemPost.find_by(post_id: 45, item: Item.find_by(item_number: 345)).blank?
ItemPost.create!(post_id: 45, item: Item.find_by(item_number: 346)) if Item.find_by(item_number: 346).present? && ItemPost.find_by(post_id: 45, item: Item.find_by(item_number: 346)).blank?
ItemPost.create!(post_id: 45, item: Item.find_by(item_number: 347)) if Item.find_by(item_number: 347).present? && ItemPost.find_by(post_id: 45, item: Item.find_by(item_number: 347)).blank?
ItemPost.create!(post_id: 45, item: Item.find_by(item_number: 348)) if Item.find_by(item_number: 348).present? && ItemPost.find_by(post_id: 45, item: Item.find_by(item_number: 348)).blank?
ItemPost.create!(post_id: 45, item: Item.find_by(item_number: 349)) if Item.find_by(item_number: 349).present? && ItemPost.find_by(post_id: 45, item: Item.find_by(item_number: 349)).blank?
ItemPost.create!(post_id: 45, item: Item.find_by(item_number: 350)) if Item.find_by(item_number: 350).present? && ItemPost.find_by(post_id: 45, item: Item.find_by(item_number: 350)).blank?
ItemPost.create!(post_id: 46, item: Item.find_by(item_number: 351)) if Item.find_by(item_number: 351).present? && ItemPost.find_by(post_id: 46, item: Item.find_by(item_number: 351)).blank?
ItemPost.create!(post_id: 47, item: Item.find_by(item_number: 352)) if Item.find_by(item_number: 352).present? && ItemPost.find_by(post_id: 47, item: Item.find_by(item_number: 352)).blank?
ItemPost.create!(post_id: 47, item: Item.find_by(item_number: 353)) if Item.find_by(item_number: 353).present? && ItemPost.find_by(post_id: 47, item: Item.find_by(item_number: 353)).blank?
ItemPost.create!(post_id: 47, item: Item.find_by(item_number: 354)) if Item.find_by(item_number: 354).present? && ItemPost.find_by(post_id: 47, item: Item.find_by(item_number: 354)).blank?
ItemPost.create!(post_id: 47, item: Item.find_by(item_number: 355)) if Item.find_by(item_number: 355).present? && ItemPost.find_by(post_id: 47, item: Item.find_by(item_number: 355)).blank?
ItemPost.create!(post_id: 48, item: Item.find_by(item_number: 356)) if Item.find_by(item_number: 356).present? && ItemPost.find_by(post_id: 48, item: Item.find_by(item_number: 356)).blank?
ItemPost.create!(post_id: 48, item: Item.find_by(item_number: 357)) if Item.find_by(item_number: 357).present? && ItemPost.find_by(post_id: 48, item: Item.find_by(item_number: 357)).blank?
ItemPost.create!(post_id: 49, item: Item.find_by(item_number: 358)) if Item.find_by(item_number: 358).present? && ItemPost.find_by(post_id: 49, item: Item.find_by(item_number: 358)).blank?
ItemPost.create!(post_id: 49, item: Item.find_by(item_number: 359)) if Item.find_by(item_number: 359).present? && ItemPost.find_by(post_id: 49, item: Item.find_by(item_number: 359)).blank?
ItemPost.create!(post_id: 49, item: Item.find_by(item_number: 360)) if Item.find_by(item_number: 360).present? && ItemPost.find_by(post_id: 49, item: Item.find_by(item_number: 360)).blank?
ItemPost.create!(post_id: 49, item: Item.find_by(item_number: 361)) if Item.find_by(item_number: 361).present? && ItemPost.find_by(post_id: 49, item: Item.find_by(item_number: 361)).blank?
ItemPost.create!(post_id: 49, item: Item.find_by(item_number: 362)) if Item.find_by(item_number: 362).present? && ItemPost.find_by(post_id: 49, item: Item.find_by(item_number: 362)).blank?
ItemPost.create!(post_id: 49, item: Item.find_by(item_number: 363)) if Item.find_by(item_number: 363).present? && ItemPost.find_by(post_id: 49, item: Item.find_by(item_number: 363)).blank?
ItemPost.create!(post_id: 49, item: Item.find_by(item_number: 364)) if Item.find_by(item_number: 364).present? && ItemPost.find_by(post_id: 49, item: Item.find_by(item_number: 364)).blank?
ItemPost.create!(post_id: 49, item: Item.find_by(item_number: 365)) if Item.find_by(item_number: 365).present? && ItemPost.find_by(post_id: 49, item: Item.find_by(item_number: 365)).blank?
ItemPost.create!(post_id: 50, item: Item.find_by(item_number: 366)) if Item.find_by(item_number: 366).present? && ItemPost.find_by(post_id: 50, item: Item.find_by(item_number: 366)).blank?
ItemPost.create!(post_id: 50, item: Item.find_by(item_number: 367)) if Item.find_by(item_number: 367).present? && ItemPost.find_by(post_id: 50, item: Item.find_by(item_number: 367)).blank?
ItemPost.create!(post_id: 50, item: Item.find_by(item_number: 368)) if Item.find_by(item_number: 368).present? && ItemPost.find_by(post_id: 50, item: Item.find_by(item_number: 368)).blank?
ItemPost.create!(post_id: 50, item: Item.find_by(item_number: 369)) if Item.find_by(item_number: 369).present? && ItemPost.find_by(post_id: 50, item: Item.find_by(item_number: 369)).blank?
ItemPost.create!(post_id: 50, item: Item.find_by(item_number: 370)) if Item.find_by(item_number: 370).present? && ItemPost.find_by(post_id: 50, item: Item.find_by(item_number: 370)).blank?
ItemPost.create!(post_id: 50, item: Item.find_by(item_number: 371)) if Item.find_by(item_number: 371).present? && ItemPost.find_by(post_id: 50, item: Item.find_by(item_number: 371)).blank?
ItemPost.create!(post_id: 50, item: Item.find_by(item_number: 372)) if Item.find_by(item_number: 372).present? && ItemPost.find_by(post_id: 50, item: Item.find_by(item_number: 372)).blank?
ItemPost.create!(post_id: 50, item: Item.find_by(item_number: 373)) if Item.find_by(item_number: 373).present? && ItemPost.find_by(post_id: 50, item: Item.find_by(item_number: 373)).blank?
ItemPost.create!(post_id: 50, item: Item.find_by(item_number: 374)) if Item.find_by(item_number: 374).present? && ItemPost.find_by(post_id: 50, item: Item.find_by(item_number: 374)).blank?
ItemPost.create!(post_id: 50, item: Item.find_by(item_number: 375)) if Item.find_by(item_number: 375).present? && ItemPost.find_by(post_id: 50, item: Item.find_by(item_number: 375)).blank?
ItemPost.create!(post_id: 50, item: Item.find_by(item_number: 376)) if Item.find_by(item_number: 376).present? && ItemPost.find_by(post_id: 50, item: Item.find_by(item_number: 376)).blank?
ItemPost.create!(post_id: 3, item: Item.find_by(item_number: 377)) if Item.find_by(item_number: 377).present? && ItemPost.find_by(post_id: 3, item: Item.find_by(item_number: 377)).blank?
ItemPost.create!(post_id: 3, item: Item.find_by(item_number: 378)) if Item.find_by(item_number: 378).present? && ItemPost.find_by(post_id: 3, item: Item.find_by(item_number: 378)).blank?
ItemPost.create!(post_id: 3, item: Item.find_by(item_number: 379)) if Item.find_by(item_number: 379).present? && ItemPost.find_by(post_id: 3, item: Item.find_by(item_number: 379)).blank?
ItemPost.create!(post_id: 3, item: Item.find_by(item_number: 380)) if Item.find_by(item_number: 380).present? && ItemPost.find_by(post_id: 3, item: Item.find_by(item_number: 380)).blank?
ItemPost.create!(post_id: 3, item: Item.find_by(item_number: 382)) if Item.find_by(item_number: 382).present? && ItemPost.find_by(post_id: 3, item: Item.find_by(item_number: 382)).blank?
ItemPost.create!(post_id: 3, item: Item.find_by(item_number: 383)) if Item.find_by(item_number: 383).present? && ItemPost.find_by(post_id: 3, item: Item.find_by(item_number: 383)).blank?
ItemPost.create!(post_id: 3, item: Item.find_by(item_number: 384)) if Item.find_by(item_number: 384).present? && ItemPost.find_by(post_id: 3, item: Item.find_by(item_number: 384)).blank?
ItemPost.create!(post_id: 3, item: Item.find_by(item_number: 385)) if Item.find_by(item_number: 385).present? && ItemPost.find_by(post_id: 3, item: Item.find_by(item_number: 385)).blank?
ItemPost.create!(post_id: 3, item: Item.find_by(item_number: 386)) if Item.find_by(item_number: 386).present? && ItemPost.find_by(post_id: 3, item: Item.find_by(item_number: 386)).blank?
ItemPost.create!(post_id: 3, item: Item.find_by(item_number: 387)) if Item.find_by(item_number: 387).present? && ItemPost.find_by(post_id: 3, item: Item.find_by(item_number: 387)).blank?
ItemPost.create!(post_id: 51, item: Item.find_by(item_number: 388)) if Item.find_by(item_number: 388).present? && ItemPost.find_by(post_id: 51, item: Item.find_by(item_number: 388)).blank?
ItemPost.create!(post_id: 51, item: Item.find_by(item_number: 389)) if Item.find_by(item_number: 389).present? && ItemPost.find_by(post_id: 51, item: Item.find_by(item_number: 389)).blank?
ItemPost.create!(post_id: 51, item: Item.find_by(item_number: 390)) if Item.find_by(item_number: 390).present? && ItemPost.find_by(post_id: 51, item: Item.find_by(item_number: 390)).blank?
ItemPost.create!(post_id: 51, item: Item.find_by(item_number: 391)) if Item.find_by(item_number: 391).present? && ItemPost.find_by(post_id: 51, item: Item.find_by(item_number: 391)).blank?
ItemPost.create!(post_id: 51, item: Item.find_by(item_number: 392)) if Item.find_by(item_number: 392).present? && ItemPost.find_by(post_id: 51, item: Item.find_by(item_number: 392)).blank?
ItemPost.create!(post_id: 51, item: Item.find_by(item_number: 393)) if Item.find_by(item_number: 393).present? && ItemPost.find_by(post_id: 51, item: Item.find_by(item_number: 393)).blank?
ItemPost.create!(post_id: 51, item: Item.find_by(item_number: 394)) if Item.find_by(item_number: 394).present? && ItemPost.find_by(post_id: 51, item: Item.find_by(item_number: 394)).blank?
ItemPost.create!(post_id: 51, item: Item.find_by(item_number: 395)) if Item.find_by(item_number: 395).present? && ItemPost.find_by(post_id: 51, item: Item.find_by(item_number: 395)).blank?
ItemPost.create!(post_id: 51, item: Item.find_by(item_number: 396)) if Item.find_by(item_number: 396).present? && ItemPost.find_by(post_id: 51, item: Item.find_by(item_number: 396)).blank?
ItemPost.create!(post_id: 51, item: Item.find_by(item_number: 397)) if Item.find_by(item_number: 397).present? && ItemPost.find_by(post_id: 51, item: Item.find_by(item_number: 397)).blank?
ItemPost.create!(post_id: 51, item: Item.find_by(item_number: 398)) if Item.find_by(item_number: 398).present? && ItemPost.find_by(post_id: 51, item: Item.find_by(item_number: 398)).blank?
ItemPost.create!(post_id: 52, item: Item.find_by(item_number: 399)) if Item.find_by(item_number: 399).present? && ItemPost.find_by(post_id: 52, item: Item.find_by(item_number: 399)).blank?
ItemPost.create!(post_id: 52, item: Item.find_by(item_number: 400)) if Item.find_by(item_number: 400).present? && ItemPost.find_by(post_id: 52, item: Item.find_by(item_number: 400)).blank?
ItemPost.create!(post_id: 52, item: Item.find_by(item_number: 401)) if Item.find_by(item_number: 401).present? && ItemPost.find_by(post_id: 52, item: Item.find_by(item_number: 401)).blank?
ItemPost.create!(post_id: 52, item: Item.find_by(item_number: 402)) if Item.find_by(item_number: 402).present? && ItemPost.find_by(post_id: 52, item: Item.find_by(item_number: 402)).blank?
ItemPost.create!(post_id: 52, item: Item.find_by(item_number: 403)) if Item.find_by(item_number: 403).present? && ItemPost.find_by(post_id: 52, item: Item.find_by(item_number: 403)).blank?
ItemPost.create!(post_id: 52, item: Item.find_by(item_number: 404)) if Item.find_by(item_number: 404).present? && ItemPost.find_by(post_id: 52, item: Item.find_by(item_number: 404)).blank?
ItemPost.create!(post_id: 52, item: Item.find_by(item_number: 405)) if Item.find_by(item_number: 405).present? && ItemPost.find_by(post_id: 52, item: Item.find_by(item_number: 405)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 406)) if Item.find_by(item_number: 406).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 406)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 407)) if Item.find_by(item_number: 407).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 407)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 408)) if Item.find_by(item_number: 408).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 408)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 409)) if Item.find_by(item_number: 409).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 409)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 410)) if Item.find_by(item_number: 410).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 410)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 411)) if Item.find_by(item_number: 411).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 411)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 412)) if Item.find_by(item_number: 412).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 412)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 413)) if Item.find_by(item_number: 413).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 413)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 414)) if Item.find_by(item_number: 414).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 414)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 415)) if Item.find_by(item_number: 415).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 415)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 416)) if Item.find_by(item_number: 416).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 416)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 417)) if Item.find_by(item_number: 417).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 417)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 418)) if Item.find_by(item_number: 418).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 418)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 419)) if Item.find_by(item_number: 419).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 419)).blank?
ItemPost.create!(post_id: 53, item: Item.find_by(item_number: 420)) if Item.find_by(item_number: 420).present? && ItemPost.find_by(post_id: 53, item: Item.find_by(item_number: 420)).blank?
ItemPost.create!(post_id: 55, item: Item.find_by(item_number: 421)) if Item.find_by(item_number: 421).present? && ItemPost.find_by(post_id: 55, item: Item.find_by(item_number: 421)).blank?
ItemPost.create!(post_id: 55, item: Item.find_by(item_number: 422)) if Item.find_by(item_number: 422).present? && ItemPost.find_by(post_id: 55, item: Item.find_by(item_number: 422)).blank?
ItemPost.create!(post_id: 55, item: Item.find_by(item_number: 423)) if Item.find_by(item_number: 423).present? && ItemPost.find_by(post_id: 55, item: Item.find_by(item_number: 423)).blank?
ItemPost.create!(post_id: 55, item: Item.find_by(item_number: 424)) if Item.find_by(item_number: 424).present? && ItemPost.find_by(post_id: 55, item: Item.find_by(item_number: 424)).blank?
ItemPost.create!(post_id: 55, item: Item.find_by(item_number: 425)) if Item.find_by(item_number: 425).present? && ItemPost.find_by(post_id: 55, item: Item.find_by(item_number: 425)).blank?
ItemPost.create!(post_id: 55, item: Item.find_by(item_number: 426)) if Item.find_by(item_number: 426).present? && ItemPost.find_by(post_id: 55, item: Item.find_by(item_number: 426)).blank?
ItemPost.create!(post_id: 56, item: Item.find_by(item_number: 427)) if Item.find_by(item_number: 427).present? && ItemPost.find_by(post_id: 56, item: Item.find_by(item_number: 427)).blank?
ItemPost.create!(post_id: 56, item: Item.find_by(item_number: 428)) if Item.find_by(item_number: 428).present? && ItemPost.find_by(post_id: 56, item: Item.find_by(item_number: 428)).blank?
ItemPost.create!(post_id: 57, item: Item.find_by(item_number: 429)) if Item.find_by(item_number: 429).present? && ItemPost.find_by(post_id: 57, item: Item.find_by(item_number: 429)).blank?
ItemPost.create!(post_id: 57, item: Item.find_by(item_number: 430)) if Item.find_by(item_number: 430).present? && ItemPost.find_by(post_id: 57, item: Item.find_by(item_number: 430)).blank?
ItemPost.create!(post_id: 57, item: Item.find_by(item_number: 431)) if Item.find_by(item_number: 431).present? && ItemPost.find_by(post_id: 57, item: Item.find_by(item_number: 431)).blank?
ItemPost.create!(post_id: 57, item: Item.find_by(item_number: 432)) if Item.find_by(item_number: 432).present? && ItemPost.find_by(post_id: 57, item: Item.find_by(item_number: 432)).blank?
ItemPost.create!(post_id: 57, item: Item.find_by(item_number: 433)) if Item.find_by(item_number: 433).present? && ItemPost.find_by(post_id: 57, item: Item.find_by(item_number: 433)).blank?
ItemPost.create!(post_id: 57, item: Item.find_by(item_number: 434)) if Item.find_by(item_number: 434).present? && ItemPost.find_by(post_id: 57, item: Item.find_by(item_number: 434)).blank?
ItemPost.create!(post_id: 57, item: Item.find_by(item_number: 435)) if Item.find_by(item_number: 435).present? && ItemPost.find_by(post_id: 57, item: Item.find_by(item_number: 435)).blank?
ItemPost.create!(post_id: 57, item: Item.find_by(item_number: 436)) if Item.find_by(item_number: 436).present? && ItemPost.find_by(post_id: 57, item: Item.find_by(item_number: 436)).blank?
ItemPost.create!(post_id: 57, item: Item.find_by(item_number: 437)) if Item.find_by(item_number: 437).present? && ItemPost.find_by(post_id: 57, item: Item.find_by(item_number: 437)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 438)) if Item.find_by(item_number: 438).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 438)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 439)) if Item.find_by(item_number: 439).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 439)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 440)) if Item.find_by(item_number: 440).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 440)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 441)) if Item.find_by(item_number: 441).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 441)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 442)) if Item.find_by(item_number: 442).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 442)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 443)) if Item.find_by(item_number: 443).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 443)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 444)) if Item.find_by(item_number: 444).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 444)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 445)) if Item.find_by(item_number: 445).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 445)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 446)) if Item.find_by(item_number: 446).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 446)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 447)) if Item.find_by(item_number: 447).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 447)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 448)) if Item.find_by(item_number: 448).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 448)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 449)) if Item.find_by(item_number: 449).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 449)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 450)) if Item.find_by(item_number: 450).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 450)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 451)) if Item.find_by(item_number: 451).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 451)).blank?
ItemPost.create!(post_id: 58, item: Item.find_by(item_number: 452)) if Item.find_by(item_number: 452).present? && ItemPost.find_by(post_id: 58, item: Item.find_by(item_number: 452)).blank?
ItemPost.create!(post_id: 59, item: Item.find_by(item_number: 453)) if Item.find_by(item_number: 453).present? && ItemPost.find_by(post_id: 59, item: Item.find_by(item_number: 453)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 454)) if Item.find_by(item_number: 454).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 454)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 455)) if Item.find_by(item_number: 455).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 455)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 456)) if Item.find_by(item_number: 456).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 456)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 457)) if Item.find_by(item_number: 457).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 457)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 458)) if Item.find_by(item_number: 458).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 458)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 459)) if Item.find_by(item_number: 459).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 459)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 460)) if Item.find_by(item_number: 460).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 460)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 461)) if Item.find_by(item_number: 461).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 461)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 462)) if Item.find_by(item_number: 462).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 462)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 463)) if Item.find_by(item_number: 463).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 463)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 464)) if Item.find_by(item_number: 464).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 464)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 465)) if Item.find_by(item_number: 465).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 465)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 466)) if Item.find_by(item_number: 466).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 466)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 467)) if Item.find_by(item_number: 467).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 467)).blank?
ItemPost.create!(post_id: 60, item: Item.find_by(item_number: 468)) if Item.find_by(item_number: 468).present? && ItemPost.find_by(post_id: 60, item: Item.find_by(item_number: 468)).blank?
ItemPost.create!(post_id: 61, item: Item.find_by(item_number: 469)) if Item.find_by(item_number: 469).present? && ItemPost.find_by(post_id: 61, item: Item.find_by(item_number: 469)).blank?
ItemPost.create!(post_id: 61, item: Item.find_by(item_number: 470)) if Item.find_by(item_number: 470).present? && ItemPost.find_by(post_id: 61, item: Item.find_by(item_number: 470)).blank?
ItemPost.create!(post_id: 61, item: Item.find_by(item_number: 471)) if Item.find_by(item_number: 471).present? && ItemPost.find_by(post_id: 61, item: Item.find_by(item_number: 471)).blank?
ItemPost.create!(post_id: 61, item: Item.find_by(item_number: 472)) if Item.find_by(item_number: 472).present? && ItemPost.find_by(post_id: 61, item: Item.find_by(item_number: 472)).blank?
ItemPost.create!(post_id: 61, item: Item.find_by(item_number: 473)) if Item.find_by(item_number: 473).present? && ItemPost.find_by(post_id: 61, item: Item.find_by(item_number: 473)).blank?
ItemPost.create!(post_id: 61, item: Item.find_by(item_number: 474)) if Item.find_by(item_number: 474).present? && ItemPost.find_by(post_id: 61, item: Item.find_by(item_number: 474)).blank?
ItemPost.create!(post_id: 61, item: Item.find_by(item_number: 475)) if Item.find_by(item_number: 475).present? && ItemPost.find_by(post_id: 61, item: Item.find_by(item_number: 475)).blank?
ItemPost.create!(post_id: 61, item: Item.find_by(item_number: 476)) if Item.find_by(item_number: 476).present? && ItemPost.find_by(post_id: 61, item: Item.find_by(item_number: 476)).blank?
ItemPost.create!(post_id: 62, item: Item.find_by(item_number: 477)) if Item.find_by(item_number: 477).present? && ItemPost.find_by(post_id: 62, item: Item.find_by(item_number: 477)).blank?
ItemPost.create!(post_id: 63, item: Item.find_by(item_number: 478)) if Item.find_by(item_number: 478).present? && ItemPost.find_by(post_id: 63, item: Item.find_by(item_number: 478)).blank?
ItemPost.create!(post_id: 63, item: Item.find_by(item_number: 479)) if Item.find_by(item_number: 479).present? && ItemPost.find_by(post_id: 63, item: Item.find_by(item_number: 479)).blank?
ItemPost.create!(post_id: 64, item: Item.find_by(item_number: 480)) if Item.find_by(item_number: 480).present? && ItemPost.find_by(post_id: 64, item: Item.find_by(item_number: 480)).blank?
ItemPost.create!(post_id: 64, item: Item.find_by(item_number: 481)) if Item.find_by(item_number: 481).present? && ItemPost.find_by(post_id: 64, item: Item.find_by(item_number: 481)).blank?
ItemPost.create!(post_id: 64, item: Item.find_by(item_number: 482)) if Item.find_by(item_number: 482).present? && ItemPost.find_by(post_id: 64, item: Item.find_by(item_number: 482)).blank?
ItemPost.create!(post_id: 64, item: Item.find_by(item_number: 483)) if Item.find_by(item_number: 483).present? && ItemPost.find_by(post_id: 64, item: Item.find_by(item_number: 483)).blank?
ItemPost.create!(post_id: 64, item: Item.find_by(item_number: 484)) if Item.find_by(item_number: 484).present? && ItemPost.find_by(post_id: 64, item: Item.find_by(item_number: 484)).blank?
ItemPost.create!(post_id: 64, item: Item.find_by(item_number: 485)) if Item.find_by(item_number: 485).present? && ItemPost.find_by(post_id: 64, item: Item.find_by(item_number: 485)).blank?
ItemPost.create!(post_id: 64, item: Item.find_by(item_number: 486)) if Item.find_by(item_number: 486).present? && ItemPost.find_by(post_id: 64, item: Item.find_by(item_number: 486)).blank?
ItemPost.create!(post_id: 65, item: Item.find_by(item_number: 487)) if Item.find_by(item_number: 487).present? && ItemPost.find_by(post_id: 65, item: Item.find_by(item_number: 487)).blank?
ItemPost.create!(post_id: 65, item: Item.find_by(item_number: 488)) if Item.find_by(item_number: 488).present? && ItemPost.find_by(post_id: 65, item: Item.find_by(item_number: 488)).blank?
ItemPost.create!(post_id: 65, item: Item.find_by(item_number: 489)) if Item.find_by(item_number: 489).present? && ItemPost.find_by(post_id: 65, item: Item.find_by(item_number: 489)).blank?
ItemPost.create!(post_id: 65, item: Item.find_by(item_number: 490)) if Item.find_by(item_number: 490).present? && ItemPost.find_by(post_id: 65, item: Item.find_by(item_number: 490)).blank?
ItemPost.create!(post_id: 65, item: Item.find_by(item_number: 491)) if Item.find_by(item_number: 491).present? && ItemPost.find_by(post_id: 65, item: Item.find_by(item_number: 491)).blank?
ItemPost.create!(post_id: 65, item: Item.find_by(item_number: 492)) if Item.find_by(item_number: 492).present? && ItemPost.find_by(post_id: 65, item: Item.find_by(item_number: 492)).blank?
ItemPost.create!(post_id: 66, item: Item.find_by(item_number: 493)) if Item.find_by(item_number: 493).present? && ItemPost.find_by(post_id: 66, item: Item.find_by(item_number: 493)).blank?
ItemPost.create!(post_id: 66, item: Item.find_by(item_number: 494)) if Item.find_by(item_number: 494).present? && ItemPost.find_by(post_id: 66, item: Item.find_by(item_number: 494)).blank?
ItemPost.create!(post_id: 66, item: Item.find_by(item_number: 495)) if Item.find_by(item_number: 495).present? && ItemPost.find_by(post_id: 66, item: Item.find_by(item_number: 495)).blank?
ItemPost.create!(post_id: 67, item: Item.find_by(item_number: 496)) if Item.find_by(item_number: 496).present? && ItemPost.find_by(post_id: 67, item: Item.find_by(item_number: 496)).blank?
ItemPost.create!(post_id: 68, item: Item.find_by(item_number: 497)) if Item.find_by(item_number: 497).present? && ItemPost.find_by(post_id: 68, item: Item.find_by(item_number: 497)).blank?
ItemPost.create!(post_id: 68, item: Item.find_by(item_number: 498)) if Item.find_by(item_number: 498).present? && ItemPost.find_by(post_id: 68, item: Item.find_by(item_number: 498)).blank?
ItemPost.create!(post_id: 68, item: Item.find_by(item_number: 499)) if Item.find_by(item_number: 499).present? && ItemPost.find_by(post_id: 68, item: Item.find_by(item_number: 499)).blank?
ItemPost.create!(post_id: 68, item: Item.find_by(item_number: 500)) if Item.find_by(item_number: 500).present? && ItemPost.find_by(post_id: 68, item: Item.find_by(item_number: 500)).blank?
ItemPost.create!(post_id: 68, item: Item.find_by(item_number: 501)) if Item.find_by(item_number: 501).present? && ItemPost.find_by(post_id: 68, item: Item.find_by(item_number: 501)).blank?
ItemPost.create!(post_id: 68, item: Item.find_by(item_number: 502)) if Item.find_by(item_number: 502).present? && ItemPost.find_by(post_id: 68, item: Item.find_by(item_number: 502)).blank?
ItemPost.create!(post_id: 68, item: Item.find_by(item_number: 503)) if Item.find_by(item_number: 503).present? && ItemPost.find_by(post_id: 68, item: Item.find_by(item_number: 503)).blank?
ItemPost.create!(post_id: 68, item: Item.find_by(item_number: 504)) if Item.find_by(item_number: 504).present? && ItemPost.find_by(post_id: 68, item: Item.find_by(item_number: 504)).blank?
ItemPost.create!(post_id: 68, item: Item.find_by(item_number: 505)) if Item.find_by(item_number: 505).present? && ItemPost.find_by(post_id: 68, item: Item.find_by(item_number: 505)).blank?
ItemPost.create!(post_id: 68, item: Item.find_by(item_number: 506)) if Item.find_by(item_number: 506).present? && ItemPost.find_by(post_id: 68, item: Item.find_by(item_number: 506)).blank?
ItemPost.create!(post_id: 69, item: Item.find_by(item_number: 507)) if Item.find_by(item_number: 507).present? && ItemPost.find_by(post_id: 69, item: Item.find_by(item_number: 507)).blank?
ItemPost.create!(post_id: 70, item: Item.find_by(item_number: 508)) if Item.find_by(item_number: 508).present? && ItemPost.find_by(post_id: 70, item: Item.find_by(item_number: 508)).blank?
ItemPost.create!(post_id: 70, item: Item.find_by(item_number: 509)) if Item.find_by(item_number: 509).present? && ItemPost.find_by(post_id: 70, item: Item.find_by(item_number: 509)).blank?
ItemPost.create!(post_id: 70, item: Item.find_by(item_number: 510)) if Item.find_by(item_number: 510).present? && ItemPost.find_by(post_id: 70, item: Item.find_by(item_number: 510)).blank?
ItemPost.create!(post_id: 71, item: Item.find_by(item_number: 511)) if Item.find_by(item_number: 511).present? && ItemPost.find_by(post_id: 71, item: Item.find_by(item_number: 511)).blank?
ItemPost.create!(post_id: 71, item: Item.find_by(item_number: 512)) if Item.find_by(item_number: 512).present? && ItemPost.find_by(post_id: 71, item: Item.find_by(item_number: 512)).blank?
ItemPost.create!(post_id: 71, item: Item.find_by(item_number: 513)) if Item.find_by(item_number: 513).present? && ItemPost.find_by(post_id: 71, item: Item.find_by(item_number: 513)).blank?
ItemPost.create!(post_id: 71, item: Item.find_by(item_number: 514)) if Item.find_by(item_number: 514).present? && ItemPost.find_by(post_id: 71, item: Item.find_by(item_number: 514)).blank?
ItemPost.create!(post_id: 71, item: Item.find_by(item_number: 515)) if Item.find_by(item_number: 515).present? && ItemPost.find_by(post_id: 71, item: Item.find_by(item_number: 515)).blank?
ItemPost.create!(post_id: 71, item: Item.find_by(item_number: 516)) if Item.find_by(item_number: 516).present? && ItemPost.find_by(post_id: 71, item: Item.find_by(item_number: 516)).blank?
ItemPost.create!(post_id: 71, item: Item.find_by(item_number: 517)) if Item.find_by(item_number: 517).present? && ItemPost.find_by(post_id: 71, item: Item.find_by(item_number: 517)).blank?
ItemPost.create!(post_id: 71, item: Item.find_by(item_number: 518)) if Item.find_by(item_number: 518).present? && ItemPost.find_by(post_id: 71, item: Item.find_by(item_number: 518)).blank?
ItemPost.create!(post_id: 71, item: Item.find_by(item_number: 519)) if Item.find_by(item_number: 519).present? && ItemPost.find_by(post_id: 71, item: Item.find_by(item_number: 519)).blank?
ItemPost.create!(post_id: 72, item: Item.find_by(item_number: 520)) if Item.find_by(item_number: 520).present? && ItemPost.find_by(post_id: 72, item: Item.find_by(item_number: 520)).blank?
ItemPost.create!(post_id: 73, item: Item.find_by(item_number: 521)) if Item.find_by(item_number: 521).present? && ItemPost.find_by(post_id: 73, item: Item.find_by(item_number: 521)).blank?
ItemPost.create!(post_id: 74, item: Item.find_by(item_number: 522)) if Item.find_by(item_number: 522).present? && ItemPost.find_by(post_id: 74, item: Item.find_by(item_number: 522)).blank?
ItemPost.create!(post_id: 74, item: Item.find_by(item_number: 523)) if Item.find_by(item_number: 523).present? && ItemPost.find_by(post_id: 74, item: Item.find_by(item_number: 523)).blank?
ItemPost.create!(post_id: 75, item: Item.find_by(item_number: 524)) if Item.find_by(item_number: 524).present? && ItemPost.find_by(post_id: 75, item: Item.find_by(item_number: 524)).blank?
ItemPost.create!(post_id: 75, item: Item.find_by(item_number: 525)) if Item.find_by(item_number: 525).present? && ItemPost.find_by(post_id: 75, item: Item.find_by(item_number: 525)).blank?
ItemPost.create!(post_id: 75, item: Item.find_by(item_number: 526)) if Item.find_by(item_number: 526).present? && ItemPost.find_by(post_id: 75, item: Item.find_by(item_number: 526)).blank?
ItemPost.create!(post_id: 76, item: Item.find_by(item_number: 527)) if Item.find_by(item_number: 527).present? && ItemPost.find_by(post_id: 76, item: Item.find_by(item_number: 527)).blank?
ItemPost.create!(post_id: 76, item: Item.find_by(item_number: 528)) if Item.find_by(item_number: 528).present? && ItemPost.find_by(post_id: 76, item: Item.find_by(item_number: 528)).blank?
ItemPost.create!(post_id: 76, item: Item.find_by(item_number: 529)) if Item.find_by(item_number: 529).present? && ItemPost.find_by(post_id: 76, item: Item.find_by(item_number: 529)).blank?
ItemPost.create!(post_id: 76, item: Item.find_by(item_number: 530)) if Item.find_by(item_number: 530).present? && ItemPost.find_by(post_id: 76, item: Item.find_by(item_number: 530)).blank?
ItemPost.create!(post_id: 76, item: Item.find_by(item_number: 531)) if Item.find_by(item_number: 531).present? && ItemPost.find_by(post_id: 76, item: Item.find_by(item_number: 531)).blank?
ItemPost.create!(post_id: 76, item: Item.find_by(item_number: 532)) if Item.find_by(item_number: 532).present? && ItemPost.find_by(post_id: 76, item: Item.find_by(item_number: 532)).blank?
ItemPost.create!(post_id: 77, item: Item.find_by(item_number: 533)) if Item.find_by(item_number: 533).present? && ItemPost.find_by(post_id: 77, item: Item.find_by(item_number: 533)).blank?
ItemPost.create!(post_id: 77, item: Item.find_by(item_number: 534)) if Item.find_by(item_number: 534).present? && ItemPost.find_by(post_id: 77, item: Item.find_by(item_number: 534)).blank?
ItemPost.create!(post_id: 77, item: Item.find_by(item_number: 535)) if Item.find_by(item_number: 535).present? && ItemPost.find_by(post_id: 77, item: Item.find_by(item_number: 535)).blank?
ItemPost.create!(post_id: 77, item: Item.find_by(item_number: 536)) if Item.find_by(item_number: 536).present? && ItemPost.find_by(post_id: 77, item: Item.find_by(item_number: 536)).blank?
ItemPost.create!(post_id: 77, item: Item.find_by(item_number: 537)) if Item.find_by(item_number: 537).present? && ItemPost.find_by(post_id: 77, item: Item.find_by(item_number: 537)).blank?
ItemPost.create!(post_id: 77, item: Item.find_by(item_number: 538)) if Item.find_by(item_number: 538).present? && ItemPost.find_by(post_id: 77, item: Item.find_by(item_number: 538)).blank?
ItemPost.create!(post_id: 77, item: Item.find_by(item_number: 539)) if Item.find_by(item_number: 539).present? && ItemPost.find_by(post_id: 77, item: Item.find_by(item_number: 539)).blank?
ItemPost.create!(post_id: 77, item: Item.find_by(item_number: 540)) if Item.find_by(item_number: 540).present? && ItemPost.find_by(post_id: 77, item: Item.find_by(item_number: 540)).blank?
ItemPost.create!(post_id: 77, item: Item.find_by(item_number: 541)) if Item.find_by(item_number: 541).present? && ItemPost.find_by(post_id: 77, item: Item.find_by(item_number: 541)).blank?
ItemPost.create!(post_id: 78, item: Item.find_by(item_number: 542)) if Item.find_by(item_number: 542).present? && ItemPost.find_by(post_id: 78, item: Item.find_by(item_number: 542)).blank?
ItemPost.create!(post_id: 78, item: Item.find_by(item_number: 543)) if Item.find_by(item_number: 543).present? && ItemPost.find_by(post_id: 78, item: Item.find_by(item_number: 543)).blank?
ItemPost.create!(post_id: 78, item: Item.find_by(item_number: 544)) if Item.find_by(item_number: 544).present? && ItemPost.find_by(post_id: 78, item: Item.find_by(item_number: 544)).blank?
ItemPost.create!(post_id: 78, item: Item.find_by(item_number: 545)) if Item.find_by(item_number: 545).present? && ItemPost.find_by(post_id: 78, item: Item.find_by(item_number: 545)).blank?
ItemPost.create!(post_id: 78, item: Item.find_by(item_number: 546)) if Item.find_by(item_number: 546).present? && ItemPost.find_by(post_id: 78, item: Item.find_by(item_number: 546)).blank?
ItemPost.create!(post_id: 78, item: Item.find_by(item_number: 547)) if Item.find_by(item_number: 547).present? && ItemPost.find_by(post_id: 78, item: Item.find_by(item_number: 547)).blank?
ItemPost.create!(post_id: 78, item: Item.find_by(item_number: 548)) if Item.find_by(item_number: 548).present? && ItemPost.find_by(post_id: 78, item: Item.find_by(item_number: 548)).blank?
ItemPost.create!(post_id: 78, item: Item.find_by(item_number: 549)) if Item.find_by(item_number: 549).present? && ItemPost.find_by(post_id: 78, item: Item.find_by(item_number: 549)).blank?
ItemPost.create!(post_id: 78, item: Item.find_by(item_number: 550)) if Item.find_by(item_number: 550).present? && ItemPost.find_by(post_id: 78, item: Item.find_by(item_number: 550)).blank?
ItemPost.create!(post_id: 78, item: Item.find_by(item_number: 551)) if Item.find_by(item_number: 551).present? && ItemPost.find_by(post_id: 78, item: Item.find_by(item_number: 551)).blank?
ItemPost.create!(post_id: 79, item: Item.find_by(item_number: 552)) if Item.find_by(item_number: 552).present? && ItemPost.find_by(post_id: 79, item: Item.find_by(item_number: 552)).blank?
ItemPost.create!(post_id: 79, item: Item.find_by(item_number: 553)) if Item.find_by(item_number: 553).present? && ItemPost.find_by(post_id: 79, item: Item.find_by(item_number: 553)).blank?
ItemPost.create!(post_id: 79, item: Item.find_by(item_number: 554)) if Item.find_by(item_number: 554).present? && ItemPost.find_by(post_id: 79, item: Item.find_by(item_number: 554)).blank?
ItemPost.create!(post_id: 79, item: Item.find_by(item_number: 555)) if Item.find_by(item_number: 555).present? && ItemPost.find_by(post_id: 79, item: Item.find_by(item_number: 555)).blank?
ItemPost.create!(post_id: 79, item: Item.find_by(item_number: 556)) if Item.find_by(item_number: 556).present? && ItemPost.find_by(post_id: 79, item: Item.find_by(item_number: 556)).blank?
ItemPost.create!(post_id: 79, item: Item.find_by(item_number: 557)) if Item.find_by(item_number: 557).present? && ItemPost.find_by(post_id: 79, item: Item.find_by(item_number: 557)).blank?
ItemPost.create!(post_id: 79, item: Item.find_by(item_number: 558)) if Item.find_by(item_number: 558).present? && ItemPost.find_by(post_id: 79, item: Item.find_by(item_number: 558)).blank?
ItemPost.create!(post_id: 79, item: Item.find_by(item_number: 559)) if Item.find_by(item_number: 559).present? && ItemPost.find_by(post_id: 79, item: Item.find_by(item_number: 559)).blank?
ItemPost.create!(post_id: 80, item: Item.find_by(item_number: 560)) if Item.find_by(item_number: 560).present? && ItemPost.find_by(post_id: 80, item: Item.find_by(item_number: 560)).blank?
ItemPost.create!(post_id: 80, item: Item.find_by(item_number: 561)) if Item.find_by(item_number: 561).present? && ItemPost.find_by(post_id: 80, item: Item.find_by(item_number: 561)).blank?
ItemPost.create!(post_id: 80, item: Item.find_by(item_number: 562)) if Item.find_by(item_number: 562).present? && ItemPost.find_by(post_id: 80, item: Item.find_by(item_number: 562)).blank?
ItemPost.create!(post_id: 80, item: Item.find_by(item_number: 563)) if Item.find_by(item_number: 563).present? && ItemPost.find_by(post_id: 80, item: Item.find_by(item_number: 563)).blank?
ItemPost.create!(post_id: 80, item: Item.find_by(item_number: 564)) if Item.find_by(item_number: 564).present? && ItemPost.find_by(post_id: 80, item: Item.find_by(item_number: 564)).blank?
ItemPost.create!(post_id: 80, item: Item.find_by(item_number: 565)) if Item.find_by(item_number: 565).present? && ItemPost.find_by(post_id: 80, item: Item.find_by(item_number: 565)).blank?
ItemPost.create!(post_id: 80, item: Item.find_by(item_number: 566)) if Item.find_by(item_number: 566).present? && ItemPost.find_by(post_id: 80, item: Item.find_by(item_number: 566)).blank?
ItemPost.create!(post_id: 80, item: Item.find_by(item_number: 567)) if Item.find_by(item_number: 567).present? && ItemPost.find_by(post_id: 80, item: Item.find_by(item_number: 567)).blank?
ItemPost.create!(post_id: 81, item: Item.find_by(item_number: 568)) if Item.find_by(item_number: 568).present? && ItemPost.find_by(post_id: 81, item: Item.find_by(item_number: 568)).blank?
ItemPost.create!(post_id: 82, item: Item.find_by(item_number: 569)) if Item.find_by(item_number: 569).present? && ItemPost.find_by(post_id: 82, item: Item.find_by(item_number: 569)).blank?
ItemPost.create!(post_id: 82, item: Item.find_by(item_number: 570)) if Item.find_by(item_number: 570).present? && ItemPost.find_by(post_id: 82, item: Item.find_by(item_number: 570)).blank?
ItemPost.create!(post_id: 82, item: Item.find_by(item_number: 571)) if Item.find_by(item_number: 571).present? && ItemPost.find_by(post_id: 82, item: Item.find_by(item_number: 571)).blank?
ItemPost.create!(post_id: 82, item: Item.find_by(item_number: 572)) if Item.find_by(item_number: 572).present? && ItemPost.find_by(post_id: 82, item: Item.find_by(item_number: 572)).blank?
ItemPost.create!(post_id: 82, item: Item.find_by(item_number: 573)) if Item.find_by(item_number: 573).present? && ItemPost.find_by(post_id: 82, item: Item.find_by(item_number: 573)).blank?
ItemPost.create!(post_id: 82, item: Item.find_by(item_number: 574)) if Item.find_by(item_number: 574).present? && ItemPost.find_by(post_id: 82, item: Item.find_by(item_number: 574)).blank?
ItemPost.create!(post_id: 82, item: Item.find_by(item_number: 575)) if Item.find_by(item_number: 575).present? && ItemPost.find_by(post_id: 82, item: Item.find_by(item_number: 575)).blank?
ItemPost.create!(post_id: 82, item: Item.find_by(item_number: 576)) if Item.find_by(item_number: 576).present? && ItemPost.find_by(post_id: 82, item: Item.find_by(item_number: 576)).blank?
ItemPost.create!(post_id: 82, item: Item.find_by(item_number: 577)) if Item.find_by(item_number: 577).present? && ItemPost.find_by(post_id: 82, item: Item.find_by(item_number: 577)).blank?
ItemPost.create!(post_id: 82, item: Item.find_by(item_number: 578)) if Item.find_by(item_number: 578).present? && ItemPost.find_by(post_id: 82, item: Item.find_by(item_number: 578)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 579)) if Item.find_by(item_number: 579).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 579)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 580)) if Item.find_by(item_number: 580).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 580)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 581)) if Item.find_by(item_number: 581).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 581)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 582)) if Item.find_by(item_number: 582).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 582)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 583)) if Item.find_by(item_number: 583).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 583)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 584)) if Item.find_by(item_number: 584).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 584)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 585)) if Item.find_by(item_number: 585).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 585)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 586)) if Item.find_by(item_number: 586).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 586)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 587)) if Item.find_by(item_number: 587).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 587)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 588)) if Item.find_by(item_number: 588).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 588)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 589)) if Item.find_by(item_number: 589).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 589)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 590)) if Item.find_by(item_number: 590).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 590)).blank?
ItemPost.create!(post_id: 83, item: Item.find_by(item_number: 591)) if Item.find_by(item_number: 591).present? && ItemPost.find_by(post_id: 83, item: Item.find_by(item_number: 591)).blank?
ItemPost.create!(post_id: 84, item: Item.find_by(item_number: 592)) if Item.find_by(item_number: 592).present? && ItemPost.find_by(post_id: 84, item: Item.find_by(item_number: 592)).blank?
ItemPost.create!(post_id: 84, item: Item.find_by(item_number: 593)) if Item.find_by(item_number: 593).present? && ItemPost.find_by(post_id: 84, item: Item.find_by(item_number: 593)).blank?
ItemPost.create!(post_id: 84, item: Item.find_by(item_number: 594)) if Item.find_by(item_number: 594).present? && ItemPost.find_by(post_id: 84, item: Item.find_by(item_number: 594)).blank?
ItemPost.create!(post_id: 86, item: Item.find_by(item_number: 595)) if Item.find_by(item_number: 595).present? && ItemPost.find_by(post_id: 86, item: Item.find_by(item_number: 595)).blank?
ItemPost.create!(post_id: 86, item: Item.find_by(item_number: 596)) if Item.find_by(item_number: 596).present? && ItemPost.find_by(post_id: 86, item: Item.find_by(item_number: 596)).blank?
ItemPost.create!(post_id: 86, item: Item.find_by(item_number: 597)) if Item.find_by(item_number: 597).present? && ItemPost.find_by(post_id: 86, item: Item.find_by(item_number: 597)).blank?
ItemPost.create!(post_id: 86, item: Item.find_by(item_number: 598)) if Item.find_by(item_number: 598).present? && ItemPost.find_by(post_id: 86, item: Item.find_by(item_number: 598)).blank?
ItemPost.create!(post_id: 86, item: Item.find_by(item_number: 599)) if Item.find_by(item_number: 599).present? && ItemPost.find_by(post_id: 86, item: Item.find_by(item_number: 599)).blank?
ItemPost.create!(post_id: 86, item: Item.find_by(item_number: 600)) if Item.find_by(item_number: 600).present? && ItemPost.find_by(post_id: 86, item: Item.find_by(item_number: 600)).blank?
ItemPost.create!(post_id: 86, item: Item.find_by(item_number: 601)) if Item.find_by(item_number: 601).present? && ItemPost.find_by(post_id: 86, item: Item.find_by(item_number: 601)).blank?
ItemPost.create!(post_id: 86, item: Item.find_by(item_number: 602)) if Item.find_by(item_number: 602).present? && ItemPost.find_by(post_id: 86, item: Item.find_by(item_number: 602)).blank?
ItemPost.create!(post_id: 86, item: Item.find_by(item_number: 603)) if Item.find_by(item_number: 603).present? && ItemPost.find_by(post_id: 86, item: Item.find_by(item_number: 603)).blank?
ItemPost.create!(post_id: 86, item: Item.find_by(item_number: 604)) if Item.find_by(item_number: 604).present? && ItemPost.find_by(post_id: 86, item: Item.find_by(item_number: 604)).blank?
ItemPost.create!(post_id: 86, item: Item.find_by(item_number: 605)) if Item.find_by(item_number: 605).present? && ItemPost.find_by(post_id: 86, item: Item.find_by(item_number: 605)).blank?
ItemPost.create!(post_id: 86, item: Item.find_by(item_number: 606)) if Item.find_by(item_number: 606).present? && ItemPost.find_by(post_id: 86, item: Item.find_by(item_number: 606)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 607)) if Item.find_by(item_number: 607).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 607)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 608)) if Item.find_by(item_number: 608).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 608)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 609)) if Item.find_by(item_number: 609).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 609)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 610)) if Item.find_by(item_number: 610).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 610)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 611)) if Item.find_by(item_number: 611).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 611)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 612)) if Item.find_by(item_number: 612).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 612)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 613)) if Item.find_by(item_number: 613).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 613)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 614)) if Item.find_by(item_number: 614).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 614)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 615)) if Item.find_by(item_number: 615).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 615)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 616)) if Item.find_by(item_number: 616).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 616)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 617)) if Item.find_by(item_number: 617).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 617)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 618)) if Item.find_by(item_number: 618).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 618)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 619)) if Item.find_by(item_number: 619).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 619)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 620)) if Item.find_by(item_number: 620).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 620)).blank?
ItemPost.create!(post_id: 85, item: Item.find_by(item_number: 621)) if Item.find_by(item_number: 621).present? && ItemPost.find_by(post_id: 85, item: Item.find_by(item_number: 621)).blank?