cosme = Category.create!(name: 'コスメ・化粧品')
cosme.children.create!(name: 'メイクアップ')
cosme.children.create!(name: 'ベースメイク')
cosme.children.create!(name: '口紅・グロス・リップライナー')
cosme.children.create!(name: 'スキンケア')
cosme.children.create!(name: 'その他')

Category.find_by(name: 'メイクアップ').children.create!(name: 'アイライナー')
Category.find_by(name: 'メイクアップ').children.create!(name: 'アイシャドウ')
Category.find_by(name: 'メイクアップ').children.create!(name: 'アイブロウ')
Category.find_by(name: 'メイクアップ').children.create!(name: 'マスカラ')
Category.find_by(name: 'ベースメイク').children.create!(name: '化粧下地')
Category.find_by(name: 'ベースメイク').children.create!(name: 'ファンデーション')
Category.find_by(name: 'ベースメイク').children.create!(name: 'コンシーラー')
Category.find_by(name: 'ベースメイク').children.create!(name: 'フェイスパウダー')
Category.find_by(name: 'ベースメイク').children.create!(name: 'チーク')
Category.find_by(name: 'ベースメイク').children.create!(name: 'シェーダー')
Category.find_by(name: 'ベースメイク').children.create!(name: 'ハイライト')
Category.find_by(name: 'ベースメイク').children.create!(name: 'BBクリーム')
Category.find_by(name: '口紅・グロス・リップライナー').children.create!(name: 'リップクリーム・リップケア')
Category.find_by(name: '口紅・グロス・リップライナー').children.create!(name: '口紅・グロス・リップライナー')
Category.find_by(name: 'スキンケア').children.create!(name: '化粧水')
Category.find_by(name: 'スキンケア').children.create!(name: '乳液')
Category.find_by(name: 'スキンケア').children.create!(name: 'パック・マスク')
Category.find_by(name: 'スキンケア').children.create!(name: '美容液')
Category.find_by(name: 'スキンケア').children.create!(name: 'スキンケアクリーム')
Category.find_by(name: 'スキンケア').children.create!(name: 'スキンケアオイル')
Category.find_by(name: 'スキンケア').children.create!(name: 'ピーリング')
Category.find_by(name: 'スキンケア').children.create!(name: '洗顔料')
Category.find_by(name: 'スキンケア').children.create!(name: '洗顔石鹸')
Category.find_by(name: 'スキンケア').children.create!(name: 'クレンジング')
Category.find_by(name: 'スキンケア').children.create!(name: 'アイケア')
Category.find_by(name: 'その他').children.create!(name: 'メイク雑貨・小物')
Category.find_by(name: 'その他').children.create!(name: 'ネイル用品')
Category.find_by(name: 'その他').children.create!(name: '香水')
Category.find_by(name: 'その他').children.create!(name: 'サプリメント')