PostItemCategory.create!(item: Item.find_by(item_number: 297), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 297).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 297)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 298), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 298).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 298)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 299), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 299).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 299)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 300), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 300).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 300)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 301), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 301).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 301)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 302), category: Category.find_by(name: 'メイク雑貨・小物')) if Item.find_by(item_number: 302).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 302)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 303), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 303).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 303)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 304), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 304).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 304)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 305), category: Category.find(20)) if Item.find_by(item_number: 305).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 305)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 306), category: Category.find_by(name: 'スキンケアクリーム')) if Item.find_by(item_number: 306).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 306)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 307), category: Category.find_by(name: '洗顔料')) if Item.find_by(item_number: 307).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 307)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 308), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 308).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 308)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 309), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 309).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 309)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 310), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 310).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 310)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 311), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 311).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 311)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 312), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 312).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 312)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 313), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 313).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 313)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 314), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 314).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 314)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 315), category: Category.find_by(name: 'メイク雑貨・小物')) if Item.find_by(item_number: 315).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 315)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 316), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 316).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 316)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 317), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 317).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 317)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 318), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 318).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 318)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 319), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 319).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 319)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 320), category: Category.find_by(name: '化粧水')) if Item.find_by(item_number: 320).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 320)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 321), category: Category.find_by(name: '洗顔料')) if Item.find_by(item_number: 321).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 321)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 322), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 322).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 322)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 323), category: Category.find_by(name: 'メイク雑貨・小物')) if Item.find_by(item_number: 323).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 323)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 324), category: Category.find_by(name: 'パック・マスク')) if Item.find_by(item_number: 324).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 324)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 325), category: Category.find_by(name: 'メイク雑貨・小物')) if Item.find_by(item_number: 325).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 325)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 326), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 326).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 326)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 327), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 327).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 327)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 328), category: Category.find_by(name: '化粧水')) if Item.find_by(item_number: 328).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 328)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 329), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 329).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 329)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 330), category: Category.find_by(name: '化粧水')) if Item.find_by(item_number: 330).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 330)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 331), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 331).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 331)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 332), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 332).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 332)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 333), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 333).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 333)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 334), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 334).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 334)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 335), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 335).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 335)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 336), category: Category.find_by(name: 'シェーダー')) if Item.find_by(item_number: 336).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 336)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 337), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 337).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 337)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 338), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 338).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 338)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 339), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 339).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 339)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 340), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 340).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 340)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 341), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 341).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 341)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 342), category: Category.find(20)) if Item.find_by(item_number: 342).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 342)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 343), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 343).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 343)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 344), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 344).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 344)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 345), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 345).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 345)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 346), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 346).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 346)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 347), category: Category.find_by(name: 'ハイライト')) if Item.find_by(item_number: 347).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 347)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 348), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 348).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 348)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 349), category: Category.find(20)) if Item.find_by(item_number: 349).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 349)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 350), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 350).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 350)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 351), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 351).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 351)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 352), category: Category.find_by(name: 'パック・マスク')) if Item.find_by(item_number: 352).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 352)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 353), category: Category.find_by(name: 'パック・マスク')) if Item.find_by(item_number: 353).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 353)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 354), category: Category.find_by(name: 'スキンケアクリーム')) if Item.find_by(item_number: 354).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 354)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 355), category: Category.find_by(name: 'クレンジング')) if Item.find_by(item_number: 355).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 355)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 356), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 356).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 356)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 357), category: Category.find_by(name: 'スキンケアクリーム')) if Item.find_by(item_number: 357).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 357)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 358), category: Category.find_by(name: '美容液')) if Item.find_by(item_number: 358).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 358)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 359), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 359).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 359)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 360), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 360).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 360)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 361), category: Category.find_by(name: 'ハイライト')) if Item.find_by(item_number: 361).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 361)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 362), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 362).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 362)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 363), category: Category.find(20)) if Item.find_by(item_number: 363).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 363)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 364), category: Category.find(20)) if Item.find_by(item_number: 364).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 364)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 365), category: Category.find(20)) if Item.find_by(item_number: 365).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 365)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 366), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 366).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 366)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 367), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 367).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 367)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 368), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 368).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 368)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 369), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 369).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 369)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 370), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 370).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 370)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 371), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 371).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 371)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 372), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 372).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 372)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 373), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 373).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 373)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 374), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 374).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 374)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 375), category: Category.find(20)) if Item.find_by(item_number: 375).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 375)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 376), category: Category.find(20)) if Item.find_by(item_number: 376).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 376)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 377), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 377).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 377)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 378), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 378).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 378)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 379), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 379).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 379)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 380), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 380).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 380)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 382), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 382).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 382)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 383), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 383).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 383)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 384), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 384).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 384)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 385), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 385).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 385)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 386), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 386).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 386)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 387), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 387).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 387)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 388), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 388).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 388)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 389), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 389).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 389)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 390), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 390).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 390)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 391), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 391).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 391)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 392), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 392).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 392)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 393), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 393).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 393)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 394), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 394).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 394)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 395), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 395).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 395)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 396), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 396).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 396)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 397), category: Category.find(20)) if Item.find_by(item_number: 397).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 397)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 398), category: Category.find_by(name: 'ハイライト')) if Item.find_by(item_number: 398).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 398)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 399), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 399).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 399)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 400), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 400).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 400)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 401), category: Category.find_by(name: 'メイク雑貨・小物')) if Item.find_by(item_number: 401).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 401)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 402), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 402).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 402)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 403), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 403).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 403)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 404), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 404).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 404)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 405), category: Category.find(20)) if Item.find_by(item_number: 405).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 405)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 406), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 406).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 406)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 407), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 407).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 407)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 408), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 408).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 408)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 409), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 409).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 409)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 410), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 410).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 410)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 411), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 411).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 411)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 412), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 412).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 412)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 413), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 413).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 413)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 414), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 414).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 414)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 415), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 415).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 415)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 416), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 416).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 416)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 417), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 417).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 417)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 418), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 418).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 418)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 419), category: Category.find_by(name: 'シェーダー')) if Item.find_by(item_number: 419).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 419)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 420), category: Category.find(20)) if Item.find_by(item_number: 420).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 420)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 421), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 421).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 421)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 422), category: Category.find_by(name: 'メイク雑貨・小物')) if Item.find_by(item_number: 422).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 422)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 423), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 423).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 423)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 424), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 424).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 424)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 425), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 425).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 425)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 426), category: Category.find(20)) if Item.find_by(item_number: 426).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 426)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 427), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 427).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 427)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 428), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 428).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 428)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 429), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 429).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 429)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 430), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 430).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 430)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 431), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 431).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 431)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 432), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 432).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 432)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 433), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 433).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 433)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 434), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 434).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 434)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 435), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 435).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 435)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 436), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 436).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 436)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 437), category: Category.find(20)) if Item.find_by(item_number: 437).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 437)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 438), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 438).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 438)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 439), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 439).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 439)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 440), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 440).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 440)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 441), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 441).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 441)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 442), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 442).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 442)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 443), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 443).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 443)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 444), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 444).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 444)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 445), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 445).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 445)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 446), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 446).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 446)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 447), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 447).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 447)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 448), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 448).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 448)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 449), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 449).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 449)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 450), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 450).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 450)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 451), category: Category.find(20)) if Item.find_by(item_number: 451).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 451)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 452), category: Category.find(20)) if Item.find_by(item_number: 452).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 452)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 453), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 453).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 453)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 454), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 454).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 454)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 455), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 455).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 455)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 456), category: Category.find_by(name: 'リップクリーム・リップケア')) if Item.find_by(item_number: 456).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 456)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 457), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 457).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 457)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 458), category: Category.find(20)) if Item.find_by(item_number: 458).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 458)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 459), category: Category.find(20)) if Item.find_by(item_number: 459).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 459)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 460), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 460).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 460)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 461), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 461).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 461)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 462), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 462).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 462)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 463), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 463).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 463)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 464), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 464).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 464)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 465), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 465).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 465)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 466), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 466).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 466)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 467), category: Category.find(20)) if Item.find_by(item_number: 467).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 467)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 468), category: Category.find(20)) if Item.find_by(item_number: 468).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 468)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 469), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 469).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 469)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 470), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 470).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 470)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 471), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 471).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 471)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 472), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 472).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 472)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 473), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 473).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 473)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 474), category: Category.find(20)) if Item.find_by(item_number: 474).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 474)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 475), category: Category.find(20)) if Item.find_by(item_number: 475).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 475)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 476), category: Category.find(20)) if Item.find_by(item_number: 476).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 476)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 477), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 477).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 477)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 478), category: Category.find_by(name: 'クレンジング')) if Item.find_by(item_number: 478).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 478)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 479), category: Category.find_by(name: 'スキンケアクリーム')) if Item.find_by(item_number: 479).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 479)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 480), category: Category.find_by(name: 'クレンジング')) if Item.find_by(item_number: 480).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 480)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 481), category: Category.find_by(name: 'クレンジング')) if Item.find_by(item_number: 481).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 481)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 482), category: Category.find_by(name: '美容液')) if Item.find_by(item_number: 482).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 482)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 483), category: Category.find_by(name: '化粧水')) if Item.find_by(item_number: 483).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 483)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 484), category: Category.find_by(name: '美容液')) if Item.find_by(item_number: 484).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 484)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 485), category: Category.find_by(name: 'パック・マスク')) if Item.find_by(item_number: 485).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 485)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 486), category: Category.find_by(name: 'スキンケアクリーム')) if Item.find_by(item_number: 486).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 486)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 487), category: Category.find_by(name: 'ピーリング')) if Item.find_by(item_number: 487).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 487)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 488), category: Category.find_by(name: '美容液')) if Item.find_by(item_number: 488).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 488)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 489), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 489).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 489)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 490), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 490).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 490)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 491), category: Category.find(20)) if Item.find_by(item_number: 491).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 491)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 492), category: Category.find(20)) if Item.find_by(item_number: 492).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 492)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 493), category: Category.find_by(name: 'クレンジング')) if Item.find_by(item_number: 493).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 493)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 494), category: Category.find_by(name: 'クレンジング')) if Item.find_by(item_number: 494).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 494)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 495), category: Category.find_by(name: '美容液')) if Item.find_by(item_number: 495).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 495)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 496), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 496).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 496)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 497), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 497).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 497)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 498), category: Category.find_by(name: 'スキンケアクリーム')) if Item.find_by(item_number: 498).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 498)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 499), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 499).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 499)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 500), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 500).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 500)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 501), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 501).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 501)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 502), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 502).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 502)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 503), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 503).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 503)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 504), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 504).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 504)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 505), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 505).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 505)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 506), category: Category.find(20)) if Item.find_by(item_number: 506).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 506)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 507), category: Category.find_by(name: 'パック・マスク')) if Item.find_by(item_number: 507).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 507)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 508), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 508).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 508)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 509), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 509).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 509)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 510), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 510).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 510)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 511), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 511).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 511)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 512), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 512).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 512)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 513), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 513).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 513)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 514), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 514).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 514)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 515), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 515).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 515)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 516), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 516).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 516)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 517), category: Category.find(20)) if Item.find_by(item_number: 517).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 517)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 518), category: Category.find(20)) if Item.find_by(item_number: 518).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 518)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 519), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 519).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 519)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 520), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 520).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 520)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 521), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 521).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 521)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 522), category: Category.find_by(name: 'メイク雑貨・小物')) if Item.find_by(item_number: 522).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 522)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 523), category: Category.find_by(name: 'リップクリーム・リップケア')) if Item.find_by(item_number: 523).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 523)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 524), category: Category.find_by(name: 'クレンジング')) if Item.find_by(item_number: 524).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 524)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 525), category: Category.find_by(name: 'クレンジング')) if Item.find_by(item_number: 525).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 525)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 526), category: Category.find_by(name: '美容液')) if Item.find_by(item_number: 526).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 526)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 527), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 527).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 527)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 528), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 528).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 528)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 529), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 529).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 529)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 530), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 530).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 530)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 531), category: Category.find(20)) if Item.find_by(item_number: 531).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 531)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 532), category: Category.find(20)) if Item.find_by(item_number: 532).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 532)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 533), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 533).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 533)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 534), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 534).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 534)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 535), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 535).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 535)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 536), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 536).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 536)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 537), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 537).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 537)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 538), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 538).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 538)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 539), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 539).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 539)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 540), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 540).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 540)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 541), category: Category.find(20)) if Item.find_by(item_number: 541).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 541)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 542), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 542).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 542)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 543), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 543).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 543)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 544), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 544).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 544)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 545), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 545).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 545)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 546), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 546).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 546)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 547), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 547).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 547)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 548), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 548).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 548)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 549), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 549).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 549)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 550), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 550).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 550)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 551), category: Category.find(20)) if Item.find_by(item_number: 551).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 551)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 552), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 552).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 552)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 553), category: Category.find_by(name: 'パック・マスク')) if Item.find_by(item_number: 553).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 553)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 554), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 554).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 554)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 555), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 555).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 555)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 556), category: Category.find_by(name: 'パック・マスク')) if Item.find_by(item_number: 556).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 556)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 557), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 557).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 557)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 558), category: Category.find_by(name: 'クレンジング')) if Item.find_by(item_number: 558).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 558)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 559), category: Category.find(20)) if Item.find_by(item_number: 559).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 559)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 560), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 560).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 560)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 561), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 561).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 561)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 562), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 562).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 562)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 563), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 563).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 563)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 564), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 564).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 564)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 565), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 565).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 565)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 566), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 566).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 566)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 567), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 567).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 567)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 568), category: Category.find(20)) if Item.find_by(item_number: 568).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 568)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 569), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 569).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 569)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 570), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 570).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 570)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 571), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 571).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 571)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 572), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 572).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 572)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 573), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 573).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 573)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 574), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 574).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 574)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 575), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 575).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 575)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 576), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 576).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 576)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 577), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 577).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 577)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 578), category: Category.find(20)) if Item.find_by(item_number: 578).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 578)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 579), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 579).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 579)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 580), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 580).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 580)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 581), category: Category.find_by(name: 'BBクリーム')) if Item.find_by(item_number: 581).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 581)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 582), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 582).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 582)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 583), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 583).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 583)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 584), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 584).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 584)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 585), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 585).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 585)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 586), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 586).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 586)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 587), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 587).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 587)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 588), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 588).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 588)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 589), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 589).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 589)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 590), category: Category.find(20)) if Item.find_by(item_number: 590).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 590)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 591), category: Category.find_by(name: 'リップクリーム・リップケア')) if Item.find_by(item_number: 591).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 591)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 592), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 592).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 592)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 593), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 593).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 593)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 594), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 594).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 594)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 595), category: Category.find_by(name: 'パック・マスク')) if Item.find_by(item_number: 595).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 595)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 596), category: Category.find_by(name: '美容液')) if Item.find_by(item_number: 596).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 596)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 597), category: Category.find_by(name: 'アイケア')) if Item.find_by(item_number: 597).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 597)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 598), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 598).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 598)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 599), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 599).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 599)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 600), category: Category.find_by(name: 'メイク雑貨・小物')) if Item.find_by(item_number: 600).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 600)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 601), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 601).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 601)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 602), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 602).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 602)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 603), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 603).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 603)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 604), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 604).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 604)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 605), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 605).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 605)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 606), category: Category.find(20)) if Item.find_by(item_number: 606).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 606)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 607), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 607).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 607)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 608), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 608).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 608)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 609), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 609).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 609)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 610), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 610).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 610)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 611), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 611).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 611)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 612), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 612).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 612)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 613), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 613).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 613)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 614), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 614).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 614)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 615), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 615).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 615)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 616), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 616).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 616)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 617), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 617).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 617)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 618), category: Category.find(20)) if Item.find_by(item_number: 618).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 618)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 619), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 619).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 619)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 620), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 620).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 620)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 621), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 621).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 621)).blank?