ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 73)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 73)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 74)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 74)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 75)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 75)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 76)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 76)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 77)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 77)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 78)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 78)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 79)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 79)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 80)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 80)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 81)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 81)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 82)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 82)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 84)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 84)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 85)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 85)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 86)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 86)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 87)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 87)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 88)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 88)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 89)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 89)).blank?
ItemPost.create!(post_id: 18, item: Item.find_by(item_number: 90)) if ItemPost.find_by(post_id: 18, item: Item.find_by(item_number: 90)).blank?
ItemPost.create!(post_id: 19, item: Item.find_by(item_number: 91)) if ItemPost.find_by(post_id: 19, item: Item.find_by(item_number: 91)).blank?
ItemPost.create!(post_id: 19, item: Item.find_by(item_number: 92)) if ItemPost.find_by(post_id: 19, item: Item.find_by(item_number: 92)).blank?
ItemPost.create!(post_id: 19, item: Item.find_by(item_number: 93)) if ItemPost.find_by(post_id: 19, item: Item.find_by(item_number: 93)).blank?
ItemPost.create!(post_id: 19, item: Item.find_by(item_number: 94)) if ItemPost.find_by(post_id: 19, item: Item.find_by(item_number: 94)).blank?
ItemPost.create!(post_id: 20, item: Item.find_by(item_number: 96)) if ItemPost.find_by(post_id: 20, item: Item.find_by(item_number: 96)).blank?
ItemPost.create!(post_id: 20, item: Item.find_by(item_number: 97)) if ItemPost.find_by(post_id: 20, item: Item.find_by(item_number: 97)).blank?
ItemPost.create!(post_id: 20, item: Item.find_by(item_number: 98)) if ItemPost.find_by(post_id: 20, item: Item.find_by(item_number: 98)).blank?
ItemPost.create!(post_id: 20, item: Item.find_by(item_number: 99)) if ItemPost.find_by(post_id: 20, item: Item.find_by(item_number: 99)).blank?
ItemPost.create!(post_id: 20, item: Item.find_by(item_number: 100)) if ItemPost.find_by(post_id: 20, item: Item.find_by(item_number: 100)).blank?
ItemPost.create!(post_id: 20, item: Item.find_by(item_number: 101)) if ItemPost.find_by(post_id: 20, item: Item.find_by(item_number: 101)).blank?
ItemPost.create!(post_id: 20, item: Item.find_by(item_number: 102)) if ItemPost.find_by(post_id: 20, item: Item.find_by(item_number: 102)).blank?
ItemPost.create!(post_id: 21, item: Item.find_by(item_number: 103)) if ItemPost.find_by(post_id: 21, item: Item.find_by(item_number: 103)).blank?
ItemPost.create!(post_id: 21, item: Item.find_by(item_number: 104)) if ItemPost.find_by(post_id: 21, item: Item.find_by(item_number: 104)).blank?
ItemPost.create!(post_id: 21, item: Item.find_by(item_number: 105)) if ItemPost.find_by(post_id: 21, item: Item.find_by(item_number: 105)).blank?
ItemPost.create!(post_id: 21, item: Item.find_by(item_number: 106)) if ItemPost.find_by(post_id: 21, item: Item.find_by(item_number: 106)).blank?
ItemPost.create!(post_id: 22, item: Item.find_by(item_number: 107)) if ItemPost.find_by(post_id: 22, item: Item.find_by(item_number: 107)).blank?
ItemPost.create!(post_id: 22, item: Item.find_by(item_number: 108)) if ItemPost.find_by(post_id: 22, item: Item.find_by(item_number: 108)).blank?
ItemPost.create!(post_id: 22, item: Item.find_by(item_number: 109)) if ItemPost.find_by(post_id: 22, item: Item.find_by(item_number: 109)).blank?
ItemPost.create!(post_id: 22, item: Item.find_by(item_number: 110)) if ItemPost.find_by(post_id: 22, item: Item.find_by(item_number: 110)).blank?
ItemPost.create!(post_id: 22, item: Item.find_by(item_number: 111)) if ItemPost.find_by(post_id: 22, item: Item.find_by(item_number: 111)).blank?
ItemPost.create!(post_id: 22, item: Item.find_by(item_number: 112)) if ItemPost.find_by(post_id: 22, item: Item.find_by(item_number: 112)).blank?
ItemPost.create!(post_id: 22, item: Item.find_by(item_number: 113)) if ItemPost.find_by(post_id: 22, item: Item.find_by(item_number: 113)).blank?
ItemPost.create!(post_id: 22, item: Item.find_by(item_number: 114)) if ItemPost.find_by(post_id: 22, item: Item.find_by(item_number: 114)).blank?
ItemPost.create!(post_id: 22, item: Item.find_by(item_number: 116)) if ItemPost.find_by(post_id: 22, item: Item.find_by(item_number: 116)).blank?
ItemPost.create!(post_id: 23, item: Item.find_by(item_number: 119)) if ItemPost.find_by(post_id: 23, item: Item.find_by(item_number: 119)).blank?
ItemPost.create!(post_id: 23, item: Item.find_by(item_number: 120)) if ItemPost.find_by(post_id: 23, item: Item.find_by(item_number: 120)).blank?
ItemPost.create!(post_id: 23, item: Item.find_by(item_number: 122)) if ItemPost.find_by(post_id: 23, item: Item.find_by(item_number: 122)).blank?
ItemPost.create!(post_id: 14, item: Item.find_by(item_number: 123)) if ItemPost.find_by(post_id: 14, item: Item.find_by(item_number: 123)).blank?
ItemPost.create!(post_id: 14, item: Item.find_by(item_number: 124)) if ItemPost.find_by(post_id: 14, item: Item.find_by(item_number: 124)).blank?
ItemPost.create!(post_id: 14, item: Item.find_by(item_number: 125)) if ItemPost.find_by(post_id: 14, item: Item.find_by(item_number: 125)).blank?
ItemPost.create!(post_id: 14, item: Item.find_by(item_number: 126)) if ItemPost.find_by(post_id: 14, item: Item.find_by(item_number: 126)).blank?
ItemPost.create!(post_id: 14, item: Item.find_by(item_number: 127)) if ItemPost.find_by(post_id: 14, item: Item.find_by(item_number: 127)).blank?
ItemPost.create!(post_id: 14, item: Item.find_by(item_number: 128)) if ItemPost.find_by(post_id: 14, item: Item.find_by(item_number: 128)).blank?
ItemPost.create!(post_id: 14, item: Item.find_by(item_number: 129)) if ItemPost.find_by(post_id: 14, item: Item.find_by(item_number: 129)).blank?
ItemPost.create!(post_id: 14, item: Item.find_by(item_number: 131)) if ItemPost.find_by(post_id: 14, item: Item.find_by(item_number: 131)).blank?
ItemPost.create!(post_id: 15, item: Item.find_by(item_number: 132)) if ItemPost.find_by(post_id: 15, item: Item.find_by(item_number: 132)).blank?
ItemPost.create!(post_id: 15, item: Item.find_by(item_number: 134)) if ItemPost.find_by(post_id: 15, item: Item.find_by(item_number: 134)).blank?
ItemPost.create!(post_id: 15, item: Item.find_by(item_number: 135)) if ItemPost.find_by(post_id: 15, item: Item.find_by(item_number: 135)).blank?
ItemPost.create!(post_id: 15, item: Item.find_by(item_number: 136)) if ItemPost.find_by(post_id: 15, item: Item.find_by(item_number: 136)).blank?
ItemPost.create!(post_id: 15, item: Item.find_by(item_number: 138)) if ItemPost.find_by(post_id: 15, item: Item.find_by(item_number: 138)).blank?
ItemPost.create!(post_id: 15, item: Item.find_by(item_number: 139)) if ItemPost.find_by(post_id: 15, item: Item.find_by(item_number: 139)).blank?
ItemPost.create!(post_id: 15, item: Item.find_by(item_number: 140)) if ItemPost.find_by(post_id: 15, item: Item.find_by(item_number: 140)).blank?
ItemPost.create!(post_id: 15, item: Item.find_by(item_number: 141)) if ItemPost.find_by(post_id: 15, item: Item.find_by(item_number: 141)).blank?
ItemPost.create!(post_id: 16, item: Item.find_by(item_number: 142)) if ItemPost.find_by(post_id: 16, item: Item.find_by(item_number: 142)).blank?
ItemPost.create!(post_id: 16, item: Item.find_by(item_number: 143)) if ItemPost.find_by(post_id: 16, item: Item.find_by(item_number: 143)).blank?
ItemPost.create!(post_id: 16, item: Item.find_by(item_number: 144)) if ItemPost.find_by(post_id: 16, item: Item.find_by(item_number: 144)).blank?
ItemPost.create!(post_id: 16, item: Item.find_by(item_number: 145)) if ItemPost.find_by(post_id: 16, item: Item.find_by(item_number: 145)).blank?
ItemPost.create!(post_id: 16, item: Item.find_by(item_number: 146)) if ItemPost.find_by(post_id: 16, item: Item.find_by(item_number: 146)).blank?
ItemPost.create!(post_id: 16, item: Item.find_by(item_number: 152)) if ItemPost.find_by(post_id: 16, item: Item.find_by(item_number: 152)).blank?
ItemPost.create!(post_id: 16, item: Item.find_by(item_number: 153)) if ItemPost.find_by(post_id: 16, item: Item.find_by(item_number: 153)).blank?
ItemPost.create!(post_id: 16, item: Item.find_by(item_number: 154)) if ItemPost.find_by(post_id: 16, item: Item.find_by(item_number: 154)).blank?
ItemPost.create!(post_id: 16, item: Item.find_by(item_number: 155)) if ItemPost.find_by(post_id: 16, item: Item.find_by(item_number: 155)).blank?
ItemPost.create!(post_id: 16, item: Item.find_by(item_number: 156)) if ItemPost.find_by(post_id: 16, item: Item.find_by(item_number: 156)).blank?