PostItemCategory.create!(item: Item.find_by(item_number: 633), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 633).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 633)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 634), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 634).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 634)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 635), category: Category.find(20)) if Item.find_by(item_number: 635).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 635)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 636), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 636).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 636)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 637), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 637).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 637)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 638), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 638).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 638)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 639), category: Category.find_by(name: 'スキンケアクリーム')) if Item.find_by(item_number: 639).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 639)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 640), category: Category.find_by(name: 'スキンケアクリーム')) if Item.find_by(item_number: 640).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 640)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 641), category: Category.find_by(name: 'スキンケアオイル')) if Item.find_by(item_number: 641).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 641)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 643), category: Category.find_by(name: 'スキンケアクリーム')) if Item.find_by(item_number: 643).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 643)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 644), category: Category.find_by(name: 'スキンケアクリーム')) if Item.find_by(item_number: 644).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 644)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 649), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 649).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 649)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 650), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 650).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 650)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 651), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 651).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 651)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 652), category: Category.find(20)) if Item.find_by(item_number: 652).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 652)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 653), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 653).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 653)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 654), category: Category.find_by(name: '化粧水')) if Item.find_by(item_number: 654).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 654)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 655), category: Category.find_by(name: '乳液')) if Item.find_by(item_number: 655).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 655)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 657), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 657).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 657)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 658), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 658).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 658)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 659), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 659).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 659)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 660), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 660).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 660)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 661), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 661).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 661)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 662), category: Category.find(20)) if Item.find_by(item_number: 662).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 662)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 663), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 663).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 663)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 664), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 664).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 664)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 666), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 666).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 666)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 667), category: Category.find_by(name: '化粧水')) if Item.find_by(item_number: 667).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 667)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 668), category: Category.find_by(name: '美容液')) if Item.find_by(item_number: 668).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 668)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 669), category: Category.find_by(name: 'スキンケアクリーム')) if Item.find_by(item_number: 669).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 669)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 671), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 671).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 671)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 673), category: Category.find_by(name: '美容液')) if Item.find_by(item_number: 673).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 673)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 675), category: Category.find_by(name: '美容液')) if Item.find_by(item_number: 675).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 675)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 677), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 677).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 677)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 678), category: Category.find_by(name: '美容液')) if Item.find_by(item_number: 678).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 678)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 679), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 679).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 679)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 680), category: Category.find(20)) if Item.find_by(item_number: 680).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 680)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 681), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 681).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 681)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 683), category: Category.find_by(name: '化粧水')) if Item.find_by(item_number: 683).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 683)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 684), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 684).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 684)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 685), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 685).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 685)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 686), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 686).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 686)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 687), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 687).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 687)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 688), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 688).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 688)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 689), category: Category.find(20)) if Item.find_by(item_number: 689).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 689)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 690), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 690).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 690)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 691), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 691).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 691)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 692), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 692).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 692)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 693), category: Category.find(20)) if Item.find_by(item_number: 693).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 693)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 694), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 694).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 694)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 695), category: Category.find(20)) if Item.find_by(item_number: 695).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 695)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 697), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 697).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 697)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 698), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 698).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 698)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 699), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 699).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 699)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 700), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 700).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 700)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 702), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 702).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 702)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 704), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 704).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 704)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 705), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 705).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 705)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 708), category: Category.find_by(name: 'メイク雑貨・小物')) if Item.find_by(item_number: 708).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 708)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 709), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 709).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 709)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 710), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 710).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 710)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 711), category: Category.find_by(name: 'メイク雑貨・小物')) if Item.find_by(item_number: 711).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 711)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 712), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 712).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 712)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 713), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 713).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 713)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 714), category: Category.find_by(name: 'メイク雑貨・小物')) if Item.find_by(item_number: 714).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 714)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 715), category: Category.find_by(name: 'マスカラ')) if Item.find_by(item_number: 715).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 715)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 716), category: Category.find_by(name: 'ファンデーション')) if Item.find_by(item_number: 716).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 716)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 717), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 717).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 717)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 718), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 718).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 718)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 719), category: Category.find_by(name: 'フェイスパウダー')) if Item.find_by(item_number: 719).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 719)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 720), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 720).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 720)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 721), category: Category.find_by(name: 'アイブロウ')) if Item.find_by(item_number: 721).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 721)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 722), category: Category.find_by(name: 'コンシーラー')) if Item.find_by(item_number: 722).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 722)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 723), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 723).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 723)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 724), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 724).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 724)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 725), category: Category.find_by(name: 'チーク')) if Item.find_by(item_number: 725).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 725)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 726), category: Category.find(20)) if Item.find_by(item_number: 726).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 726)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 727), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 727).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 727)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 728), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 728).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 728)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 729), category: Category.find_by(name: 'アイシャドウ')) if Item.find_by(item_number: 729).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 729)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 730), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 730).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 730)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 731), category: Category.find_by(name: 'アイライナー')) if Item.find_by(item_number: 731).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 731)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 732), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 732).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 732)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 733), category: Category.find_by(name: 'その他')) if Item.find_by(item_number: 733).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 733)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 735), category: Category.find(20)) if Item.find_by(item_number: 735).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 735)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 737), category: Category.find_by(name: '化粧下地')) if Item.find_by(item_number: 737).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 737)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 738), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 738).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 738)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 739), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 739).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 739)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 740), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 740).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 740)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 741), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 741).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 741)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 742), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 742).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 742)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 743), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 743).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 743)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 744), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 744).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 744)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 745), category: Category.find_by(name: '日焼け止め・UVケア')) if Item.find_by(item_number: 745).present? && PostItemCategory.find_by(item: Item.find_by(item_number: 745)).blank?