ItemPost.create!(post_id: 1, item: Item.find_by(item_number: 1)) if ItemPost.find_by(post_id: 1, item: Item.find_by(item_number: 1)).blank?
ItemPost.create!(post_id: 1, item: Item.find_by(item_number: 2)) if ItemPost.find_by(post_id: 1, item: Item.find_by(item_number: 2)).blank?
ItemPost.create!(post_id: 1, item: Item.find_by(item_number: 3)) if ItemPost.find_by(post_id: 1, item: Item.find_by(item_number: 3)).blank?
ItemPost.create!(post_id: 1, item: Item.find_by(item_number: 4)) if ItemPost.find_by(post_id: 1, item: Item.find_by(item_number: 4)).blank?
ItemPost.create!(post_id: 1, item: Item.find_by(item_number: 5)) if ItemPost.find_by(post_id: 1, item: Item.find_by(item_number: 5)).blank?
ItemPost.create!(post_id: 2, item: Item.find_by(item_number: 6)) if ItemPost.find_by(post_id: 2, item: Item.find_by(item_number: 6)).blank?
ItemPost.create!(post_id: 2, item: Item.find_by(item_number: 7)) if ItemPost.find_by(post_id: 2, item: Item.find_by(item_number: 7)).blank?
ItemPost.create!(post_id: 2, item: Item.find_by(item_number: 8)) if ItemPost.find_by(post_id: 2, item: Item.find_by(item_number: 8)).blank?
ItemPost.create!(post_id: 2, item: Item.find_by(item_number: 9)) if ItemPost.find_by(post_id: 2, item: Item.find_by(item_number: 9)).blank?
ItemPost.create!(post_id: 4, item: Item.find_by(item_number: 10)) if ItemPost.find_by(post_id: 4, item: Item.find_by(item_number: 10)).blank?
ItemPost.create!(post_id: 4, item: Item.find_by(item_number: 11)) if ItemPost.find_by(post_id: 4, item: Item.find_by(item_number: 11)).blank?
ItemPost.create!(post_id: 4, item: Item.find_by(item_number: 12)) if ItemPost.find_by(post_id: 4, item: Item.find_by(item_number: 12)).blank?
ItemPost.create!(post_id: 4, item: Item.find_by(item_number: 13)) if ItemPost.find_by(post_id: 4, item: Item.find_by(item_number: 13)).blank?
ItemPost.create!(post_id: 4, item: Item.find_by(item_number: 14)) if ItemPost.find_by(post_id: 4, item: Item.find_by(item_number: 14)).blank?
ItemPost.create!(post_id: 4, item: Item.find_by(item_number: 15)) if ItemPost.find_by(post_id: 4, item: Item.find_by(item_number: 15)).blank?
ItemPost.create!(post_id: 4, item: Item.find_by(item_number: 16)) if ItemPost.find_by(post_id: 4, item: Item.find_by(item_number: 16)).blank?
ItemPost.create!(post_id: 4, item: Item.find_by(item_number: 17)) if ItemPost.find_by(post_id: 4, item: Item.find_by(item_number: 17)).blank?
ItemPost.create!(post_id: 10, item: Item.find_by(item_number: 18)) if ItemPost.find_by(post_id: 10, item: Item.find_by(item_number: 18)).blank?
ItemPost.create!(post_id: 10, item: Item.find_by(item_number: 19)) if ItemPost.find_by(post_id: 10, item: Item.find_by(item_number: 19)).blank?
ItemPost.create!(post_id: 10, item: Item.find_by(item_number: 20)) if ItemPost.find_by(post_id: 10, item: Item.find_by(item_number: 20)).blank?
ItemPost.create!(post_id: 10, item: Item.find_by(item_number: 21)) if ItemPost.find_by(post_id: 10, item: Item.find_by(item_number: 21)).blank?
ItemPost.create!(post_id: 5, item: Item.find_by(item_number: 22)) if ItemPost.find_by(post_id: 5, item: Item.find_by(item_number: 22)).blank?
ItemPost.create!(post_id: 5, item: Item.find_by(item_number: 23)) if ItemPost.find_by(post_id: 5, item: Item.find_by(item_number: 23)).blank?
ItemPost.create!(post_id: 5, item: Item.find_by(item_number: 24)) if ItemPost.find_by(post_id: 5, item: Item.find_by(item_number: 24)).blank?
ItemPost.create!(post_id: 5, item: Item.find_by(item_number: 26)) if ItemPost.find_by(post_id: 5, item: Item.find_by(item_number: 26)).blank?
ItemPost.create!(post_id: 5, item: Item.find_by(item_number: 27)) if ItemPost.find_by(post_id: 5, item: Item.find_by(item_number: 27)).blank?
ItemPost.create!(post_id: 5, item: Item.find_by(item_number: 28)) if ItemPost.find_by(post_id: 5, item: Item.find_by(item_number: 28)).blank?
ItemPost.create!(post_id: 5, item: Item.find_by(item_number: 29)) if ItemPost.find_by(post_id: 5, item: Item.find_by(item_number: 29)).blank?
ItemPost.create!(post_id: 5, item: Item.find_by(item_number: 30)) if ItemPost.find_by(post_id: 5, item: Item.find_by(item_number: 30)).blank?
ItemPost.create!(post_id: 5, item: Item.find_by(item_number: 31)) if ItemPost.find_by(post_id: 5, item: Item.find_by(item_number: 31)).blank?
ItemPost.create!(post_id: 6, item: Item.find_by(item_number: 32)) if ItemPost.find_by(post_id: 6, item: Item.find_by(item_number: 32)).blank?
ItemPost.create!(post_id: 6, item: Item.find_by(item_number: 33)) if ItemPost.find_by(post_id: 6, item: Item.find_by(item_number: 33)).blank?
ItemPost.create!(post_id: 7, item: Item.find_by(item_number: 36)) if ItemPost.find_by(post_id: 7, item: Item.find_by(item_number: 36)).blank?
ItemPost.create!(post_id: 8, item: Item.find_by(item_number: 37)) if ItemPost.find_by(post_id: 8, item: Item.find_by(item_number: 37)).blank?
ItemPost.create!(post_id: 8, item: Item.find_by(item_number: 38)) if ItemPost.find_by(post_id: 8, item: Item.find_by(item_number: 38)).blank?
ItemPost.create!(post_id: 9, item: Item.find_by(item_number: 39)) if ItemPost.find_by(post_id: 9, item: Item.find_by(item_number: 39)).blank?
ItemPost.create!(post_id: 9, item: Item.find_by(item_number: 40)) if ItemPost.find_by(post_id: 9, item: Item.find_by(item_number: 40)).blank?
ItemPost.create!(post_id: 9, item: Item.find_by(item_number: 41)) if ItemPost.find_by(post_id: 9, item: Item.find_by(item_number: 41)).blank?
ItemPost.create!(post_id: 11, item: Item.find_by(item_number: 43)) if ItemPost.find_by(post_id: 11, item: Item.find_by(item_number: 43)).blank?
ItemPost.create!(post_id: 12, item: Item.find_by(item_number: 44)) if ItemPost.find_by(post_id: 12, item: Item.find_by(item_number: 44)).blank?
ItemPost.create!(post_id: 12, item: Item.find_by(item_number: 45)) if ItemPost.find_by(post_id: 12, item: Item.find_by(item_number: 45)).blank?
ItemPost.create!(post_id: 12, item: Item.find_by(item_number: 46)) if ItemPost.find_by(post_id: 12, item: Item.find_by(item_number: 46)).blank?
ItemPost.create!(post_id: 12, item: Item.find_by(item_number: 47)) if ItemPost.find_by(post_id: 12, item: Item.find_by(item_number: 47)).blank?
ItemPost.create!(post_id: 12, item: Item.find_by(item_number: 48)) if ItemPost.find_by(post_id: 12, item: Item.find_by(item_number: 48)).blank?
ItemPost.create!(post_id: 12, item: Item.find_by(item_number: 49)) if ItemPost.find_by(post_id: 12, item: Item.find_by(item_number: 49)).blank?