PostItemCategory.create!(item: Item.find_by(item_number: 1), category: Category.find_by(name: '化粧水')) if PostItemCategory.find_by(item: Item.find_by(item_number: 1)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 2), category: Category.find_by(name: '美容液')) if PostItemCategory.find_by(item: Item.find_by(item_number: 2)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 3), category: Category.find_by(name: 'スキンケアクリーム')) if PostItemCategory.find_by(item: Item.find_by(item_number: 3)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 4), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 4)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 5), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 5)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 6), category: Category.find_by(name: 'ピーリング')) if PostItemCategory.find_by(item: Item.find_by(item_number: 6)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 7), category: Category.find_by(name: '美容液')) if PostItemCategory.find_by(item: Item.find_by(item_number: 7)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 8), category: Category.find_by(name: 'スキンケアクリーム')) if PostItemCategory.find_by(item: Item.find_by(item_number: 8)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 9), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 9)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 10), category: Category.find_by(name: '化粧下地')) if PostItemCategory.find_by(item: Item.find_by(item_number: 10)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 11), category: Category.find_by(name: 'ファンデーション')) if PostItemCategory.find_by(item: Item.find_by(item_number: 11)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 12), category: Category.find_by(name: 'ファンデーション')) if PostItemCategory.find_by(item: Item.find_by(item_number: 12)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 13), category: Category.find_by(name: 'アイブロウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 13)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 14), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 14)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 15), category: Category.find_by(name: 'アイライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 15)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 16), category: Category.find_by(name: 'チーク')) if PostItemCategory.find_by(item: Item.find_by(item_number: 16)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 17), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 17)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 18), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 18)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 19), category: Category.find_by(name: 'アイブロウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 19)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 20), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 20)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 21), category: Category.find_by(name: 'ハイライト')) if PostItemCategory.find_by(item: Item.find_by(item_number: 21)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 22), category: Category.find_by(name: '日焼け止め・UVケア')) if PostItemCategory.find_by(item: Item.find_by(item_number: 22)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 23), category: Category.find_by(name: 'リップクリーム・リップケア')) if PostItemCategory.find_by(item: Item.find_by(item_number: 23)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 24), category: Category.find_by(name: 'フェイスパウダー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 24)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 25), category: Category.find_by(name: 'ハイライト')) if PostItemCategory.find_by(item: Item.find_by(item_number: 25)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 26), category: Category.find_by(name: 'アイブロウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 26)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 27), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 27)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 28), category: Category.find_by(name: 'チーク')) if PostItemCategory.find_by(item: Item.find_by(item_number: 28)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 29), category: Category.find_by(name: 'マスカラ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 29)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 30), category: Category.find_by(name: 'アイブロウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 30)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 31), category: Category.find_by(name: 'フェイスパウダー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 31)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 32), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 32)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 33), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 33)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 34), category: Category.find_by(name: 'チーク')) if PostItemCategory.find_by(item: Item.find_by(item_number: 34)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 36), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 36)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 37), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 37)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 38), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 38)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 39), category: Category.find_by(name: 'クレンジング')) if PostItemCategory.find_by(item: Item.find_by(item_number: 39)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 40), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 40)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 41), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 41)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 42), category: Category.find_by(name: 'ハイライト')) if PostItemCategory.find_by(item: Item.find_by(item_number: 42)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 43), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 43)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 44), category: Category.find_by(name: 'ファンデーション')) if PostItemCategory.find_by(item: Item.find_by(item_number: 44)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 45), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 45)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 46), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 46)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 47), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 47)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 48), category: Category.find_by(name: 'アイライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 48)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 49), category: Category.find_by(name: 'チーク')) if PostItemCategory.find_by(item: Item.find_by(item_number: 49)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 50), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 50)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 51), category: Category.find_by(name: 'アイライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 51)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 52), category: Category.find_by(name: 'アイライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 52)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 53), category: Category.find_by(name: 'アイブロウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 53)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 54), category: Category.find_by(name: 'マスカラ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 54)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 55), category: Category.find_by(name: 'マスカラ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 55)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 56), category: Category.find_by(name: '化粧下地')) if PostItemCategory.find_by(item: Item.find_by(item_number: 56)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 57), category: Category.find_by(name: 'ファンデーション')) if PostItemCategory.find_by(item: Item.find_by(item_number: 57)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 58), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 58)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 59), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 59)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 60), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 60)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 61), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 61)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 62), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 62)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 63), category: Category.find_by(name: 'ハイライト')) if PostItemCategory.find_by(item: Item.find_by(item_number: 63)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 64), category: Category.find_by(name: 'リップクリーム・リップケア')) if PostItemCategory.find_by(item: Item.find_by(item_number: 64)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 65), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 65)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 67), category: Category.find_by(name: '口紅・グロス・リップライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 67)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 68), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 68)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 69), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 69)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 70), category: Category.find_by(name: 'アイライナー')) if PostItemCategory.find_by(item: Item.find_by(item_number: 70)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 71), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 71)).blank?
PostItemCategory.create!(item: Item.find_by(item_number: 72), category: Category.find_by(name: 'アイシャドウ')) if PostItemCategory.find_by(item: Item.find_by(item_number: 72)).blank?